import { t } from 'kensington';
export function reactivityKnownTradeoffs() {
  return t.section({ id: 'known-tradeoffs' }, [
    t.h2('Known tradeoffs'),
    t.p('These are deliberate simplicity choices, not bugs.'),
    t.ul([
      t.li([
        t.strong('DOM replacement, not true hydration.'),
        ' The SSR elements are replaced with a fresh ',
        t.code('toElement()'),
        ' call rather than reusing them. In practice the swap is imperceptible. It is synchronous and the visual output is identical. Transitions are suppressed automatically on SSR elements until hydration completes.',
      ]),
      t.li([t.strong('Non-interactive window.'), ` Elements are non-reactive between the browser's first paint and when the hydration script runs. This is inherent to SSR-then-hydrate.`]),
      t.li([
        t.strong('State is plaintext.'),
        ' State is embedded as a ',
        t.code('<script type="application/json">'),
        ' tag visible in page source. Do not pass secrets or tokens as hydration state.',
      ]),
      t.li([
        t.strong('Browser globals outside '),
        t.code('effect()'),
        t.strong(' will throw on the server.'),
        ' ',
        t.code('effect()'),
        ' is suppressed during server-side rendering. For browser-only code that cannot go inside ',
        t.code('effect()'),
        ': module-level code, ',
        t.code('computed()'),
        ' values, direct assignments. Use the ',
        t.code('isBrowser'),
        ' export: ',
        t.code("isBrowser && localStorage.getItem('key')"),
        '.',
      ]),
      t.li([
        t.strong('One tag, one element.'),
        ' Each tag instance maps to exactly one DOM node. Passing the same instance as a child of two different parents moves it rather than cloning it. Create separate tag instances if you need the same structure in two places.',
      ]),
      t.li([
        t.strong('Signal-driven '),
        t.code('.literal()'),
        t.strong(' does a full DOM replacement on each change.'),
        ' The entire HTML subtree between the anchor comments is torn down and re-parsed on every signal update. There is no patching. Avoid using a frequently-changing signal with large ',
        t.code('.literal()'),
        ' content.',
      ]),
      t.li([
        t.strong('Unkeyed reactive primitives inside a '),
        t.code('computed'),
        t.strong(' replace the DOM node on every outer re-render.'),
        ' This applies uniformly to ',
        t.code('signal()'),
        ', ',
        t.code('computed()'),
        ', and ',
        t.code('.transform()'),
        ' created inside a computed callback without a key. The reconciler detects the changed instance reference and swaps in a fresh node so the new instance drives it. Focus, scroll, input values, and text selection are preserved across the swap. IME composition, CSS animations in flight, pointer capture, ',
        t.code('<canvas>'),
        ' bitmaps, ',
        t.code('<iframe>'),
        ' documents, web component instance state, and third-party listeners attached outside Kensington are lost. Pass a stable key as the second argument to any of them to reuse the same instance across re-runs. The DOM node stays in place and nothing is lost.',
      ]),
      t.li([
        t.strong('Reactive element reset after removal is asynchronous.'),
        ' When a reactive element is removed from the DOM, its effects are stopped and the internal reference is cleared via MutationObserver. Calling ',
        t.code('.toElement()'),
        ' immediately after removal in synchronous code still returns the old element. Awaiting a tick (',
        t.code('await Promise.resolve()'),
        ') before the next ',
        t.code('.toElement()'),
        ' call ensures the reset has completed. Non-reactive elements are not affected: ',
        t.code('.toElement()'),
        ' returns the same node after removal and it can be re-inserted directly.',
      ]),
      t.li([
        // eslint-disable-next-line @stylistic/js/max-len -- single sentence in <strong>
        t.strong('Module-level compute calls that are never subscribed to retain their source subscriptions indefinitely.'),
        ' ',
        t.code('computed()'),
        ' auto-disposes when its last subscriber unsubscribes, but a computed that never gains a subscriber never enters that cycle. Its internal update function stays subscribed to its source signals for the lifetime of the module. Call ',
        t.code('.stop()'),
        ' explicitly on such a computed when it is no longer needed.',
      ]),
    ]),
  ]);
}
