import pluginJs from '@eslint/js';
import stylistic from '@stylistic/eslint-plugin';
import simpleImportSort from 'eslint-plugin-simple-import-sort';
import globals from 'globals';

/** @type {import('eslint').Linter.Config[]} */
export default [
  {
    'languageOptions': {
      'globals': {
        ...globals.browser,
        ...globals.node,
      },
    },
  },
  pluginJs.configs.all,
  {
    'ignores': [
      'cjs/**',
      'dist/**',
      '**/node_modules/**',
    ],
  },
  {
    'plugins': {
      '@stylistic/js': stylistic,
      'simple-import-sort': simpleImportSort,
    },
  },
  {
    'rules': {
      '@stylistic/js/array-bracket-newline': 'off',
      '@stylistic/js/array-element-newline': 'off',
      '@stylistic/js/arrow-parens': ['error', 'as-needed'],
      '@stylistic/js/brace-style': 'off',
      '@stylistic/js/comma-dangle': ['error', 'always-multiline'],
      '@stylistic/js/dot-location': ['error', 'property'],
      '@stylistic/js/function-call-argument-newline': 'off',
      '@stylistic/js/function-paren-newline': 'off',
      '@stylistic/js/implicit-arrow-linebreak': 'off',
      '@stylistic/js/indent': ['error', 2],
      '@stylistic/js/lines-around-comment': 'off',
      '@stylistic/js/lines-between-class-members': ['error', 'always', { 'exceptAfterSingleLine': true }],
      '@stylistic/js/max-len': ['error', {
        code: 120,
        ignoreComments: true,
        ignoreRegExpLiterals: true,
        ignoreStrings: true,
        ignoreTemplateLiterals: true,
        ignoreTrailingComments: true,
      }],
      '@stylistic/js/multiline-comment-style': 'off',
      '@stylistic/js/multiline-ternary': 'off',
      '@stylistic/js/newline-per-chained-call': 'off',
      '@stylistic/js/no-extra-parens': 'off',
      '@stylistic/js/no-multiple-empty-lines': ['error', { 'max': 1, 'maxEOF': 1 }],
      '@stylistic/js/object-curly-spacing': ['error', 'always'],
      '@stylistic/js/object-property-newline': 'off',
      '@stylistic/js/padded-blocks': ['error', 'never'],
      '@stylistic/js/quote-props': 'off',
      '@stylistic/js/quotes': [
        'error',
        'single',
        {
          'allowTemplateLiterals': 'always',
          'avoidEscape': true,
        },
      ],
      '@stylistic/js/semi': ['error', 'always'],
      '@stylistic/js/space-before-function-paren': [
        'error',
        {
          'anonymous': 'never',
          'asyncArrow': 'always',
          'named': 'never',
        },
      ],
      '@stylistic/js/wrap-regex': 'off',
      'arrow-body-style': 'off',
      'capitalized-comments': 'off',
      'class-methods-use-this': 'off',
      'complexity': 'off',
      'default-param-last': 'off',
      'func-style': [
        'warn',
        'declaration',
        { 'allowArrowFunctions': true },
      ],
      'id-length': 'off',
      'init-declarations': 'off',
      'max-classes-per-file': 'off',
      'max-lines': 'off',
      'max-lines-per-function': 'off',
      'max-params': 'off',
      'max-statements': 'off',
      'new-cap': 'off',
      'no-alert': 'off',
      'no-async-promise-executor': 'off',
      'no-await-in-loop': 'off',
      'no-console': 'off',
      'no-continue': 'off',
      'no-empty-function': 'off',
      'no-inline-comments': 'off',
      'no-invalid-this': 'off',
      'no-magic-numbers': 'off',
      'no-nested-ternary': 'off',
      'no-new': 'off',
      'no-param-reassign': 'off',
      'no-plusplus': 'off',
      'no-ternary': 'off',
      'no-undefined': 'off',
      'no-underscore-dangle': 'off',
      'no-unused-expressions': 'off',
      'no-unused-vars': [
        'error',
        { 'ignoreRestSiblings': true },
      ],
      'no-warning-comments': 'off',
      'one-var': 'off',
      'prefer-destructuring': 'off',
      'prefer-named-capture-group': 'off',
      'require-atomic-updates': 'off',
      'require-unicode-regexp': 'off',
      'simple-import-sort/exports': 'error',
      'simple-import-sort/imports': 'error',
      'sort-imports': 'off',
      'sort-keys': 'off',
      'sort-vars': 'off',
    },
  },
];
