import { t } from 'kensington';

import { callout } from '../../components/ui.js';
import { loc } from './helpers.js';

export function architectureInfrastructure() {
  return [
    t.section({ id: 'infrastructure' }, [
      t.h2('Validation dispatch'),
      t.p([
        'Every validation report in the library funnels through one function in ',
        loc('esm/lib/util/show-invalid.js'),
        '. ',
        t.code('showInvalid(message, validationLevel, logger)'),
        ' implements the three-level contract that the rest of the codebase relies on.',
      ]),
      t.ul([
        t.li([
          t.strong("'off'."),
          ' Does nothing. The function returns immediately without logging or throwing.',
        ]),
        t.li([
          t.strong("'warn'."),
          ' Calls ',
          t.code('logger(error.stack)'),
          ' with a stack-bearing Error.',
        ]),
        t.li([
          t.strong("'error'."),
          ' Throws the Error.',
        ]),
      ]),
      t.p([
        'The function builds an ',
        t.code('Error'),
        ' from the message and passes it through ',
        loc('esm/lib/util/filter-stack.js'),
        ' before either logging or throwing, so the surfaced stack points at the caller rather than at internal frames.',
      ]),
      callout('warning', "'off' never throws on runtime input",
        t.p([
          "Production deployments run at 'off' for performance. Because ",
          t.code('showInvalid'),
          ' is a no-op at that level, invalid runtime input is silently skipped. Render nothing, omit the attribute, filter the content item. An unexpected throw could take down a server or break a user-facing page, so every runtime validation check routes through this dispatcher. The only unconditional throws in the library are hard setup-time invariants, such as an invalid ',
          t.code('validationLevel'),
          ' value or a non-string tag name passed to tag creation.',
        ]),
      ),
    ]),

    t.section({ id: 'infra-warnings' }, [
      t.h2('Warning throttling'),
      t.p([
        loc('esm/lib/reactive/warnings.js'),
        ' owns the runtime diagnostics used by the reactive layer. It exports ',
        t.code('throttledError'),
        ', ',
        t.code('throttledWarn'),
        ', and the test helper ',
        t.code('_resetWarningThrottle'),
        '. These back the repeated diagnostics fired from ',
        loc('esm/lib/reactive/signal.js'),
        ' and ',
        loc('esm/lib/reactive/map-with-key.js'),
        '. Loop detection, invalid usage, duplicate keys.',
      ]),
      t.p([
        'Each diagnostic is keyed. A ',
        t.code('warnLastSeen'),
        ' Map records the last time each key fired. A repeated key is suppressed until ',
        t.code('WARN_THROTTLE_MS'),
        ' (1000ms) has elapsed, so a hot loop surfaces the problem once per window instead of flooding the console. ',
        t.code('_resetWarningThrottle'),
        ' clears the Map for tests.',
      ]),
      callout('note', 'Why an Error object is passed',
        t.p([
          'Both functions call ',
          t.code('console.error(msg, error)'),
          ' (or ',
          t.code('console.warn'),
          '). The message string is the first argument so test harnesses that capture only the first argument keep working. The Error is the second argument so browser DevTools render its stack with source-map mapping applied, turning minified bundle positions back into the source positions in the user\'s project.',
        ]),
      ),
    ]),

    t.section({ id: 'infra-filter-stack' }, [
      t.h2('Stack frame stripping'),
      t.p([
        loc('esm/lib/util/filter-stack.js'),
        ' strips Kensington-internal frames from an Error so warnings and validation errors point at the caller\'s code rather than at library plumbing. It is shared by ',
        loc('esm/lib/util/show-invalid.js'),
        ' and by the throttled functions in ',
        loc('esm/lib/reactive/warnings.js'),
        '.',
      ]),
      t.h3('Node.js'),
      t.p([
        'In Node the module reads ',
        t.code('import.meta.url'),
        ', which is a ',
        t.code('file:'),
        ' URL pointing at the real file on disk. It derives the ',
        t.code('esm/'),
        ' directory from that URL and removes every stack frame whose location includes that path. User frames live elsewhere, so they survive.',
      ]),
      t.h3('Browser bundle'),
      t.p([
        'In a browser bundle Kensington and user code share the same bundle URL, so there is no reliable way to tell an internal frame from an external one. Filtering by the bundle URL would strip the user\'s own frames too, leaving only native-code frames. The filter therefore preserves the full stack whenever it cannot make that distinction, including IIFE bundles where ',
        t.code('import.meta'),
        ' is absent entirely.',
      ]),
    ]),

    t.section({ id: 'infra-devtools' }, [
      t.h2('Devtools hook'),
      t.p([
        loc('esm/lib/reactive/devtools.js'),
        ' implements the ',
        t.code('window.__KENSINGTON_DEVTOOLS__'),
        ' hook. ',
        t.code('enableDevtools()'),
        ' activates the hook once. Subsequent calls are no-ops, and calling it on the server only logs a warning.',
      ]),
      t.p('The hook object exposes:'),
      t.ul([
        t.li([t.code('signals'), ', ', t.code('effects'), ', and ', t.code('bindings'), ' Maps.']),
        t.li([t.code('domTrackedCount'), '. The current count of DOM-tracked elements.']),
        t.li([
          'An event bus. ',
          t.code('on(event, cb)'),
          ', ',
          t.code('off(event, cb)'),
          ', and ',
          t.code('_emit(event, data)'),
          '.',
        ]),
      ]),
      t.p([
        'Signal IDs and effect IDs are monotonically increasing integers assigned at creation time. A ',
        t.code('signalGcRegistry'),
        ' (a ',
        t.code('FinalizationRegistry'),
        ', or a no-op stub where the constructor is unavailable) removes devtools entries for signals that are garbage-collected without an explicit ',
        t.code('.stop()'),
        ' call.',
      ]),
      t.p([
        'When a signal reaches zero subscribers its ID is added to a ',
        t.code('pendingZeroSubscribers'),
        ' Set and scheduled for removal on a ',
        t.code('queueMicrotask'),
        '. A re-subscription in the same turn cancels the removal, which is what keeps signals in the panel across a drag-reorder pause and resume. A ',
        t.code('computedSigs'),
        ' WeakSet records which signals were created via ',
        t.code('computed()'),
        ' so a sleeping computed can be restored with ',
        t.code('isComputed: true'),
        ' when it wakes.',
      ]),
      t.p([
        t.code('markNextEffectAsBinding(label)'),
        ' sets a one-shot flag that routes the next created effect into ',
        t.code('hook.bindings'),
        ' instead of ',
        t.code('hook.effects'),
        ', tagged with the given label. This is how DOM-binding effects are distinguished from user effects in the panel.',
      ]),
      callout('note', 'Disabled by default',
        t.p([
          'All exported ',
          t.code('notify*'),
          ' functions return immediately when devtools are not enabled, so the instrumentation costs nothing in production.',
        ]),
      ),
    ]),

    t.section({ id: 'infra-preserve-state' }, [
      t.h2('State preservation'),
      t.p([
        loc('esm/lib/reactive/preserve-state.js'),
        ' captures and restores user-visible DOM state across a node replacement. ',
        t.code('captureState(root)'),
        ' walks the subtree and returns a snapshot. ',
        t.code('restoreState(root, state)'),
        ' applies it to a freshly built subtree. It is used by ',
        t.code('rebuildNode'),
        ' in ',
        loc('esm/lib/reactive/reconcile.js'),
        ' when a ',
        t.code('mapWithKey'),
        ' per-key inner re-emits a fresh tag, and by ',
        t.code('hmrReplaceComponent'),
        ' in ',
        loc('esm/lib/render/hydration.js'),
        ' when a live mount is re-rendered.',
      ]),
      t.h3('What is preserved'),
      t.ul([
        t.li([
          'The focused element, recorded as a child-index path from the root, ',
          'plus its text selection range where applicable.',
        ]),
        t.li([t.code('scrollTop'), ' and ', t.code('scrollLeft'), ' on the root and every scrollable descendant.']),
        t.li([t.code('value'), ', ', t.code('checked'), ', and ', t.code('indeterminate'), ' on INPUT and TEXTAREA.']),
        t.li([t.code('value'), ' on SELECT.']),
        t.li([t.code('open'), ' on DETAILS and DIALOG.']),
      ]),
      t.p([
        'The mapping between old and new nodes is positional. It assumes the tree shape is identical between renders, which holds when only signal references differ. State for a position that does not resolve on the new tree is silently dropped.',
      ]),
      t.h3('What cannot be preserved'),
      t.p('Some state lives only on the original element instance and is lost on replacement.'),
      t.ul([
        t.li('IME composition in progress.'),
        t.li('CSS transitions and animations in flight.'),
        t.li('Pointer capture and active drag operations.'),
        t.li('Canvas bitmap contents.'),
        t.li('Iframe document state.'),
        t.li('Web component instance state.'),
        t.li('Third-party event listeners attached outside Kensington.'),
      ]),
    ]),

    t.section({ id: 'infra-duck-types' }, [
      t.h2('Cross-module duck-typing'),
      t.p([
        'A page can end up loading more than one copy of the Kensington module, for example when a dependency bundles its own copy. An ',
        t.code('instanceof'),
        ' check against this copy\'s classes would reject tags and signals built by the other copy. To accept them, the library brands its prototypes with marker properties and checks the marker instead.',
      ]),
      t.h3('Tag markers'),
      t.p([
        'In ',
        loc('esm/tag-classes/content-tag.js'),
        ', ',
        t.code('ContentTag.prototype._isKensingtonTag = true'),
        ' and ',
        t.code('ContentTag.prototype._isKensingtonContentTag = true'),
        '. The content-only marker is set on ContentTag and its subclasses. ',
        loc('esm/tag-classes/literal-tag.js'),
        ' and ',
        loc('esm/tag-classes/comment-tag.js'),
        ' each set ',
        t.code('_isKensingtonTag = true'),
        ' on their own prototype but not the content marker.',
      ]),
      t.p([
        'The local helper ',
        t.code('isKensingtonTag(c)'),
        ' checks ',
        t.code('c._isKensingtonTag === true'),
        ' and replaces the direct class checks in content validation. The separate ',
        t.code('_isKensingtonContentTag'),
        ' marker lets ',
        t.code('toElement'),
        ' recurse only into content tags, for example to pass the ',
        t.code('_inheritPersist'),
        ' option down to child ContentTag nodes.',
      ]),
      t.h3('Signal marker'),
      t.p([
        'In ',
        loc('esm/lib/reactive/signal.js'),
        ', ',
        t.code('Signal.prototype._isKensingtonSignal = true'),
        ', and ',
        t.code('isKensingtonSignal(v)'),
        ' checks ',
        t.code('v._isKensingtonSignal === true'),
        '. This is why a Signal from a different module copy is accepted anywhere a value is accepted, including by ',
        t.code('attributeValueIsValid'),
        '.',
      ]),
    ]),
  ];
}
