import { t } from 'kensington';

import { callout, code } from '../../components/ui.js';
import { loc } from './helpers.js';

export function architectureLiveSignals() {
  return t.section({ id: 'live-signals' }, [
    t.h2('Live signals'),
    t.p({ class: 'file-crumb' }, [
      'esm',
      t.span({ class: 'slash' }, '/'),
      'live',
      t.span({ class: 'slash' }, '/'),
      loc('esm/live/index.js'),
    ]),
    t.p([
      'The ',
      t.code('kensington/live'),
      ' subpath ships a small server/client runtime that lets one named primitive synchronize across browsers. Three public entry points all reachable from the unified path: ',
      t.code('liveSignal(initial, name, options?)'),
      ' for shared component code, ',
      t.code('connectLive(opts?)'),
      ' for the client, and ',
      t.code('liveServer(opts?)'),
      ' for the server. Two node-only peer deps (',
      t.code('ws'),
      ', ',
      t.code('better-sqlite3'),
      ') are loaded lazily so the unified path works in browser bundles without pulling them in.',
    ]),

    t.section({ id: 'live-state-module' }, [
      t.h3('Transport registry. state.js'),
      t.p([
        loc('esm/live/state.js'),
        ' owns the per-process current transport reference and the public ',
        t.code('liveSignal()'),
        ' factory. Both ',
        t.code('client.js'),
        ' and ',
        t.code('server.js'),
        ' install themselves via ',
        t.code('_registerTransport(transport)'),
        '. The factory reads ',
        t.code('currentTransport'),
        ' at call time and delegates to ',
        t.code('transport.getOrCreateSignal(name, initial, opts)'),
        '. With no transport registered, it returns a placeholder ',
        t.code('_signal(initial)'),
        ' tagged with ',
        t.code('_isLivePlaceholder'),
        ' and adds an entry to a module-level pending set. Pre-upgrade reads and writes both go through the default ',
        t.code('Signal.prototype'),
        ' behavior, updating only the placeholder\'s local value.',
      ]),
      t.p([
        'When ',
        t.code('_registerTransport(transport)'),
        ' runs, it drains the pending set and walks each placeholder through ',
        t.code('upgradePlaceholder(rec, transport)'),
        ', which looks up the registry-backed signal via ',
        t.code('transport.getOrCreateSignal(name, placeholder.value, opts)'),
        ' (so any pre-upgrade local write seeds the registry entry when the name is fresh), installs an internal-effect mirror that pipes ',
        t.code('real → placeholder'),
        ' via ',
        t.code('_setFromRemote'),
        ', and rewires ',
        t.code('placeholder.set'),
        ' and ',
        t.code('placeholder.stop'),
        ' to forward to ',
        t.code('real'),
        '. The user-held reference is preserved across upgrade. If the registry already holds a value for the name, the mirror\'s first run overwrites the placeholder with the authoritative value and the pre-upgrade local write is silently lost.',
      ]),
      t.p([
        t.code('validateCanWrite(value)'),
        ' inside the factory rejects invalid ',
        t.code('options.canWrite'),
        ' values eagerly (throws a ',
        t.code('TypeError'),
        ' at the call site rather than waiting for the server to reject the write). The valid forms are ',
        t.code("'any'"),
        ', ',
        t.code("'server-only'"),
        ', or a function.',
      ]),
    ]),

    t.section({ id: 'live-protocol' }, [
      t.h3('Wire protocol. protocol.js'),
      t.p([
        loc('esm/live/protocol.js'),
        ' is the single source of truth for message types and the encode/decode pair.',
      ]),
      code('javascript', `// Client → Server
{ type: 'subscribe',   name, persist? }
{ type: 'unsubscribe', name }
{ type: 'set',         name, value, ifLamport?, opId? }

// Server → Client
{ type: 'snapshot',    values: { [name]: value }, lamport }
{ type: 'update',      name, value, lamport }
{ type: 'batch-update', updates: Array<{ name, value, lamport }> }
{ type: 'set-ok',      name, lamport, opId }
{ type: 'set-fail',    name, opId, reason, value, lamport }
{ type: 'error',       name, reason }`),
      t.p([
        'Ordering is Lamport last-write-wins; the server is the sole authority for lamport assignment. Direct ',
        t.code('.set(value)'),
        ' writes omit both ',
        t.code('ifLamport'),
        ' and ',
        t.code('opId'),
        '; the server applies them unconditionally subject to ',
        t.code('canWrite'),
        '. CAS writes (',
        t.code('.set(fn)'),
        ') carry both: the server applies only when its current lamport for the name equals ',
        t.code('ifLamport'),
        '. ',
        t.code('opId'),
        ' correlates the response (',
        t.code('set-ok'),
        ' or ',
        t.code('set-fail'),
        ') back to the originating client. ',
        t.code('subscribe'),
        ' carries ',
        t.code('persist: true'),
        ' only when the client explicitly opted in; the field is omitted otherwise so the server can distinguish a positive declaration from a default-follow.',
      ]),
    ]),

    t.section({ id: 'live-client' }, [
      t.h3('Client transport. client.js'),
      t.p([
        loc('esm/live/client.js'),
        ' exports ',
        t.code('connectLive(opts)'),
        ' which constructs a ',
        t.code('ClientTransport'),
        ', registers it via ',
        t.code('_registerTransport'),
        ', and calls ',
        t.code('transport.connect()'),
        ' before returning. One transport instance per tab, multiplexed across every ',
        t.code('liveSignal'),
        '.',
      ]),

      t.section({ id: 'live-client-state' }, [
        t.h4('Instance state'),
        t.ul([
          t.li([t.code('signals'), '. Map<name, Signal>. Backs the auto-resubscribe-on-reconnect loop.']),
          t.li([t.code('initialValues'), '. Map<name, T>. First-call initial for duplicate-name mismatch warnings.']),
          t.li([t.code('persistFlags'), '. Map<name, boolean>. Re-sent on every SUBSCRIBE.']),
          t.li([
            t.code('lastSeen'),
            '. Map<name, number>. Lamport of the last applied update; used to drop stale broadcasts and as ',
            t.code('ifLamport'),
            ' for CAS.',
          ]),
          t.li([
            t.code('outbound'),
            '. Queue of frames pending an open socket (used both while disconnected and while ',
            t.code('sendPaused'),
            ' is set).',
          ]),
          t.li([
            t.code('pendingCas'),
            '. Map<opId, { name, fn, attempts, resolve, reject }>. The set(fn) retry loop suspends here.',
          ]),
          t.li([t.code('unserializableWarned'), '. Set<name> for the once-per-name JSON-stringify warning.']),
          t.li([
            t.code('status'),
            '. Reactive ',
            t.code('Signal<ConnectionStatus>'),
            '. Mirrors the WebSocket lifecycle.',
          ]),
          t.li([
            t.code('reconnectDelay'),
            ', ',
            t.code('reconnectAttempts'),
            '. Exponential-backoff state. Reset by ',
            t.code('resetReconnectState()'),
            '.',
          ]),
          t.li([t.code('closed'), '. Set true by ', t.code('close()'), '; terminal.']),
          t.li([
            t.code('sendPaused'),
            '. Set true by the internal ',
            t.code('_pauseSend()'),
            ' test hook; ',
            t.code('send()'),
            ' diverts to ',
            t.code('outbound'),
            ' while set.',
          ]),
          t.li([
            t.code('reconnectOnFocus'),
            '. Derived from the ',
            t.code('reconnect.onFocus'),
            ' option, default ',
            t.code('true'),
            '. Gates whether ',
            t.code('attachFocusListeners()'),
            ' installs the window-focus retry.',
          ]),
          t.li([
            t.code('focusListenersAttached'),
            '. Set true once ',
            t.code('attachFocusListeners()'),
            ' installs the ',
            t.code('visibilitychange'),
            '/',
            t.code('focus'),
            ' listeners. Lets ',
            t.code('close()'),
            ' know whether there is anything for ',
            t.code('detachFocusListeners()'),
            ' to remove.',
          ]),
        ]),
      ]),

      t.section({ id: 'live-client-connect' }, [
        t.h4('connect()'),
        t.p([
          'Sets ',
          t.code("status = 'connecting'"),
          ', allocates a new ',
          t.code('WebSocket(this.url)'),
          ' (bailing to ',
          t.code('scheduleReconnect'),
          ' if the constructor throws), and wires three listeners.',
        ]),
        t.ul([
          t.li([
            t.strong('open. '),
            t.code("setStatus('connected')"),
            ' → ',
            t.code('resetReconnectState()'),
            ' → walk ',
            t.code('this.signals.keys()'),
            ' and re-send a ',
            t.code('subscribe'),
            ' frame for each → drain ',
            t.code('outbound'),
            '. Both loops go through ',
            t.code('rawSendOnSocket(ws, msg)'),
            ' so the internal ',
            t.code('onFrame'),
            ' hook fires.',
          ]),
          t.li([t.strong('message. '), 'Delegates to ', t.code('handleMessage(raw)'), '.']),
          t.li([t.strong('close. '), 'Nulls ', t.code('this.ws'), ' and calls ', t.code('scheduleReconnect()'), '.']),
          t.li([
            t.strong('error. '),
            'Logged via ',
            t.code('console.error'),
            '. The reactive ',
            t.code('status'),
            ' signal covers the connection state.',
          ]),
        ]),
      ]),

      t.section({ id: 'live-client-reconnect' }, [
        t.h4('scheduleReconnect()'),
        t.p([
          'Bails when ',
          t.code('closed'),
          ' or ',
          t.code('manuallyDisconnected'),
          ' is set. Compares ',
          t.code('reconnectAttempts'),
          ' against ',
          t.code('reconnectOpts.maxRetries ?? Infinity'),
          '; on exhaustion, sets status to ',
          t.code("'disconnected'"),
          ' and stops scheduling. Otherwise sets status to ',
          t.code("'reconnecting'"),
          ' and queues a ',
          t.code('setTimeout(connect, delay)'),
          '. ',
          t.code('reconnectDelay'),
          ' doubles up to ',
          t.code('maxDelay'),
          ' after each scheduled attempt.',
        ]),
      ]),

      t.section({ id: 'live-client-focus-reconnect' }, [
        t.h4('Focus-triggered reconnect. attachFocusListeners / retryNowIfStale'),
        t.p([
          t.code('attachFocusListeners()'),
          ' runs once from the constructor when ',
          t.code('reconnect.onFocus'),
          ' is not false and ',
          t.code('window'),
          '/',
          t.code('document'),
          ' exist. It installs a ',
          t.code('visibilitychange'),
          ' listener (fires ',
          t.code('retryNowIfStale()'),
          ' when ',
          t.code('document.visibilityState === \'visible\''),
          ') and a ',
          t.code('focus'),
          ' listener on ',
          t.code('window'),
          ' (fires unconditionally). Both call the same handler; either can fire depending on whether the return is a tab switch inside one window or a switch back to the browser app itself.',
        ]),
        t.p([
          t.code('retryNowIfStale()'),
          ' bails when ',
          t.code('closed'),
          ' is set, and when ',
          t.code('status'),
          ' is not ',
          t.code("'disconnected'"),
          ' or ',
          t.code("'reconnecting'"),
          ' (already connected or mid-handshake). Otherwise it clears any pending ',
          t.code('reconnectTimer'),
          ' and calls ',
          t.code('connect()'),
          ' directly, skipping the remaining backoff wait. This intentionally bypasses an exhausted ',
          t.code('maxRetries'),
          ' cap too. A user returning to the tab is a fresh signal worth one more attempt; if it fails, the ',
          t.code('close'),
          ' listener\'s ',
          t.code('scheduleReconnect()'),
          ' call sees ',
          t.code('reconnectAttempts'),
          ' still at the exhausted count (this path does not increment it) and returns to ',
          t.code("'disconnected'"),
          ' without looping.',
        ]),
        t.p([
          'Because ',
          t.code('status'),
          ' is only ',
          t.code("'reconnecting'"),
          ' or ',
          t.code("'disconnected'"),
          ' while ',
          t.code('this.ws'),
          ' is ',
          t.code('null'),
          ', repeated focus/visibility events in quick succession are safe. The first call transitions ',
          t.code('status'),
          ' to ',
          t.code("'connecting'"),
          ' synchronously inside ',
          t.code('connect()'),
          ', so a second event arriving before the socket opens or closes sees a non-matching status and returns early.',
        ]),
        t.p([
          t.code('detachFocusListeners()'),
          ' removes both listeners; called from ',
          t.code('close()'),
          ' so a terminal transport does not leak listeners on the shared ',
          t.code('window'),
          '/',
          t.code('document'),
          ' objects.',
        ]),
      ]),

      t.section({ id: 'live-client-handle' }, [
        t.h4('handleMessage(raw)'),
        t.p([
          'Decodes the JSON, fires ',
          t.code("notifyFrame('in', msg)"),
          ', then dispatches on ',
          t.code('msg.type'),
          ':',
        ]),
        t.ul([
          t.li([
            t.code('snapshot'),
            '. Iterates ',
            t.code('msg.values'),
            '; for each pair applies ',
            t.code('sig._setFromRemote(value)'),
            ' and sets ',
            t.code('lastSeen.set(name, msg.lamport ?? 0)'),
            '.',
          ]),
          t.li([
            t.code('update'),
            ' / ',
            t.code('batch-update'),
            '. Both dispatch to ',
            t.code('applyRemoteUpdate(name, value, lamport)'),
            ', which drops stale broadcasts (',
            t.code('lamport <= seen'),
            ') and otherwise calls ',
            t.code('_setFromRemote'),
            '.',
          ]),
          t.li([
            t.code('set-ok'),
            '. Updates ',
            t.code('lastSeen'),
            ', takes the pending write entry via ',
            t.code('takePendingWrite(opId)'),
            ', resolves its promise.',
          ]),
          t.li([
            t.code('set-fail'),
            '. Takes the pending entry, applies the server\'s authoritative value to the local Signal via ',
            t.code('_setFromRemote'),
            ', bumps ',
            t.code('lastSeen'),
            ', and either retries (',
            t.code('reason === \'conflict\''),
            ' on a CAS write) via ',
            t.code('retryCas(pending)'),
            ' or rejects the promise with a ',
            t.code('LiveSetRejected'),
            ' Error.',
          ]),
          t.li([
            t.code('error'),
            '. ',
            t.code('canRead'),
            ' subscribe rejection. Logged via ',
            t.code('console.error'),
            ' since there is no per-call surface to route to.',
          ]),
        ]),
      ]),

      t.section({ id: 'live-client-getorcreate' }, [
        t.h4('getOrCreateSignal(name, initial, options)'),
        t.p([
          'On a cached hit, runs the duplicate-name mismatch warnings and returns the existing Signal.',
          ' On a miss, builds a fresh Signal and wires four hooks before returning it:',
        ]),
        t.ol({ class: 'numbered' }, [
          t.li([
            t.strong('Wrap '),
            t.code('sig.set'),
            t.strong('. '),
            'The wrapper detects ',
            t.code('typeof valueOrFn === \'function\''),
            ' and dispatches to ',
            t.code('casUpdate(...)'),
            '. The direct path checks ',
            t.code('checkSerializable'),
            ', calls the original ',
            t.code('origSet'),
            ', and sends ',
            t.code('{ type: \'set\', name, value }'),
            '.',
          ]),
          t.li([
            t.strong('Wrap '),
            t.code('sig.stop'),
            t.strong('. '),
            'After ',
            t.code('origStop'),
            ' runs, calls ',
            t.code('this.unsubscribe(name)'),
            ' to tear down the server-side subscription too.',
          ]),
          t.li([
            t.strong('Install '),
            t.code('_onZeroSubscribers'),
            ' / ',
            t.code('_onFirstSubscriber'),
            '. ',
            'When local subscribers reach zero, send ',
            t.code('MSG_UNSUBSCRIBE'),
            '. When they go from 0 → 1, send ',
            t.code('MSG_SUBSCRIBE'),
            '. The two hooks are how the Signal class\'s sleep/wake cycle reaches the transport.',
          ]),
          t.li([
            t.strong('Register and subscribe. '),
            t.code('signals.set(name, sig)'),
            ' followed by ',
            t.code('send(buildSubscribeMsg(name, persist))'),
            '.',
          ]),
        ]),
      ]),

      t.section({ id: 'live-client-cas' }, [
        t.h4('CAS. casUpdate / sendCasWrite / retryCas'),
        t.p([
          t.code('casUpdate(name, sig, origSet, fn)'),
          ' runs ',
          t.code('fn(sig.value)'),
          ' synchronously for the optimistic apply (catching throws and rejecting the returned Promise), checks serializability, calls ',
          t.code('origSet(initialNext)'),
          ' so subscribers see the new value immediately, and returns a Promise that ',
          t.code('sendCasWrite'),
          ' will eventually resolve or reject.',
        ]),
        t.p([
          t.code('sendCasWrite(pending, value)'),
          ' allocates a fresh ',
          t.code('opId'),
          ', registers the pending entry in ',
          t.code('pendingCas'),
          ', and sends ',
          t.code('{ type: \'set\', name, value, ifLamport, opId }'),
          ' with ',
          t.code('ifLamport = lastSeen.get(name) ?? 0'),
          '.',
        ]),
        t.p([
          t.code('retryCas(pending)'),
          ' bumps ',
          t.code('pending.attempts'),
          '; if it exceeds ',
          t.code('MAX_CAS_RETRIES'),
          ' (8) the promise is rejected with a "high write contention" message. Otherwise it re-runs ',
          t.code('pending.fn(sig.value)'),
          ' against the freshly-applied server value, re-checks serializability, ',
          t.code('_setFromRemote'),
          's the new local value, and reissues via ',
          t.code('sendCasWrite'),
          '.',
        ]),
      ]),

      t.section({ id: 'live-client-lifecycle' }, [
        t.h4('Lifecycle methods'),
        t.ul([
          t.li([
            t.code('close()'),
            '. Sets ',
            t.code('closed = true'),
            ', calls ',
            t.code('detachFocusListeners()'),
            ' then ',
            t.code('dropSocket()'),
            ', rejects every pending CAS with "transport closed", and transitions to ',
            t.code("'disconnected'"),
            '. Terminal.',
          ]),
          t.li([
            t.code('reconnect()'),
            '. Calls ',
            t.code('dropSocket()'),
            ', resets backoff, transitions to ',
            t.code("'reconnecting'"),
            ', and queues a ',
            t.code('connect()'),
            ' via ',
            t.code('queueMicrotask'),
            ' so any same-tick caller-side state changes (display-name edit, etc.) land in the new URL.',
          ]),
          t.li([
            'The internal ',
            t.code('_pauseSend()'),
            ' / ',
            t.code('_resumeSend()'),
            ' test hooks toggle ',
            t.code('sendPaused'),
            '. While set, ',
            t.code('send()'),
            ' diverts outgoing frames to ',
            t.code('outbound'),
            ' (reads still flow); ',
            t.code('_resumeSend()'),
            ' flushes them via ',
            t.code('rawSendOnSocket'),
            ' in FIFO order.',
          ]),
          t.li([
            t.code('unsubscribe(name)'),
            '. Drops the name from every internal Map and sends ',
            t.code('MSG_UNSUBSCRIBE'),
            '. The local Signal stays valid for reads.',
          ]),
        ]),
        t.p([
          t.code('dropSocket()'),
          ' is the shared "clear timer + close ws + null ref" helper used by both ',
          t.code('close'),
          ' and ',
          t.code('reconnect'),
          '.',
        ]),
      ]),
    ]),

    t.section({ id: 'live-server' }, [
      t.h3('Server runtime. server.js'),
      t.p([
        loc('esm/live/server.js'),
        ' exports the ',
        t.code('liveServer(opts)'),
        ' factory. The function is ',
        t.code('async'),
        ' because the sqlite store loads via dynamic import; memory awaits uniformly.',
      ]),

      t.section({ id: 'live-server-state' }, [
        t.h4('Closure state'),
        t.ul([
          t.li([t.code('registry'), '. Map<name, { value, lamport }>. The canonical in-memory store.']),
          t.li([t.code('subs'), '. Map<name, Set<socket>>. Client subscribers per name.']),
          t.li([
            t.code('nameSubscribers'),
            '. Map<name, Set<callback>>. Server-side observers (the cb registered when a server-side ',
            t.code('liveSignal'),
            ' is created).',
          ]),
          t.li([t.code('initialValues'), '. Map<name, T>. First-call initial for duplicate-name warnings.']),
          t.li([
            t.code('persistPolicy'),
            '. Map<name, boolean>. First-declaration-wins. Disk-warmed names start blank;',
            ' the next declaration sets policy.',
          ]),
          t.li([
            t.code('canWritePolicy'),
            '. Map<name, predicate>. Per-name predicates registered by server-side ',
            t.code('liveSignal(..., { canWrite })'),
            '.',
          ]),
          t.li([
            t.code('transientDropTimers'),
            '. Map<name, Timeout>. Grace-period drop timers for ',
            t.code('persist:false'),
            ' names that hit zero subscribers.',
          ]),
          t.li([
            t.code('serverSignals'),
            '. Map<name, Signal>. Cached server-side Signal instances built by ',
            t.code('makeServerSignal'),
            '.',
          ]),
          t.li([t.code('lamport'), '. The monotonic counter assigned by ', t.code('commitWrite'), '.']),
          t.li([
            t.code('attachedWss'),
            '. The ',
            t.code('WebSocketServer'),
            ' from ',
            t.code('attach()'),
            '. Null on the Bun path. ',
            t.code('close()'),
            ' tears it down.',
          ]),
          t.li([t.code('heartbeatTimer'), '. The ', t.code('setInterval'), ' handle for the heartbeat ping loop.']),
          t.li([
            t.code('pendingBroadcasts'),
            ', ',
            t.code('flushScheduled'),
            '. Outbound coalescing buffer flushed via ',
            t.code('queueMicrotask'),
            '.',
          ]),
        ]),
      ]),

      t.section({ id: 'live-server-commit' }, [
        t.h4('commitWrite / applySet'),
        t.p([
          'Every write funnels through ',
          t.code('commitWrite(name, value, fromSocket)'),
          ': increment ',
          t.code('lamport'),
          ', update ',
          t.code('registry'),
          ', persist if ',
          t.code('persistPolicy'),
          ' says so, ',
          t.code('broadcast(name, fromSocket)'),
          ' (excludes the originator), then ',
          t.code('notifyObservers(name, value)'),
          ' for the server-side observer set.',
        ]),
        t.p([
          t.code('applySet(name, value, fromSocket)'),
          ' is the thin wrapper that runs ',
          t.code('checkSerializable'),
          ' first. It is called from the wrapped server-side ',
          t.code('sig.set'),
          ' and from ',
          t.code('live.set'),
          '. ',
          t.code('handleClientSet'),
          ' bypasses ',
          t.code('applySet'),
          ' and goes straight to ',
          t.code('commitWrite'),
          ' after running its own canWrite / CAS / serializability checks.',
        ]),
      ]),

      t.section({ id: 'live-server-handle-set' }, [
        t.h4('handleClientSet / replyToClientSet / rejectClientSet'),
        t.p([
          t.code('handleClientSet'),
          ' is the entry point for inbound ',
          t.code('MSG_SET'),
          '. It assembles the ',
          t.code('{ prev, next }'),
          ' transition, runs the global ',
          t.code('canWrite'),
          ' and any per-signal predicate, runs the CAS check when ',
          t.code('ifLamport'),
          ' is present, runs ',
          t.code('checkSerializable'),
          ', then calls ',
          t.code('commitWrite'),
          ' and ',
          t.code('replyToClientSet(...true)'),
          '.',
        ]),
        t.p([
          t.code('rejectClientSet(sock, name, msg, reason)'),
          ' factors out the "rejection" path. CAS writers (',
          t.code('opId'),
          ' present) receive a typed ',
          t.code('MSG_SET_FAIL'),
          ' with the server\'s authoritative value and lamport. Non-CAS writers receive a best-effort ',
          t.code('MSG_ERROR'),
          ' instead.',
        ]),
        t.p([
          t.code('replyToClientSet(sock, name, opId, ok, reason)'),
          ' returns early when ',
          t.code('opId === undefined'),
          ' (fire-and-forget writes), otherwise sends the matching ',
          t.code('set-ok'),
          ' or ',
          t.code('set-fail'),
          ' frame.',
        ]),
      ]),

      t.section({ id: 'live-server-broadcast' }, [
        t.h4('Broadcast batching'),
        t.p([
          t.code('broadcast(name, exclude)'),
          ' pushes ',
          t.code('{ name, exclude }'),
          ' onto ',
          t.code('pendingBroadcasts'),
          ' and schedules a ',
          t.code('queueMicrotask(flushBroadcasts)'),
          ' (guarded by ',
          t.code('flushScheduled'),
          ').',
        ]),
        t.p([
          t.code('flushBroadcasts()'),
          ' groups the queued entries by destination socket. Sockets that pick up exactly one update receive a plain ',
          t.code('MSG_UPDATE'),
          '; sockets that pick up two or more receive a single ',
          t.code('MSG_BATCH_UPDATE'),
          ' carrying the array. The grouping happens at flush time, not at broadcast time, so a burst of server-side writes in one tick coalesces correctly.',
        ]),
      ]),

      t.section({ id: 'live-server-transient' }, [
        t.h4('Transient-drop machinery'),
        t.p([
          'Names declared ',
          t.code('persist: false'),
          ' are dropped from the registry ',
          t.code('TRANSIENT_GRACE_MS'),
          ' (30s) after the last subscriber leaves. The grace period covers brief reconnects and the local sleep-wake cycle.',
        ]),
        t.ul([
          t.li([
            t.code('scheduleTransientDropIfNeeded(name)'),
            '. Bails if the policy is not ',
            t.code('false'),
            ', if any subscriber remains (via ',
            t.code('hasAnySubscriber'),
            '), or if a timer already exists. Otherwise sets a ',
            t.code('setTimeout'),
            ' that is ',
            t.code('unref()'),
            '-ed so it doesn\'t pin the event loop.',
          ]),
          t.li([
            t.code('cancelTransientDrop(name)'),
            '. Clears the timer; called on every fresh ',
            t.code('MSG_SUBSCRIBE'),
            ' and every ',
            t.code('getOrCreateSignal'),
            ' on the server.',
          ]),
          t.li([
            t.code('dropTransient(name)'),
            '. The timer body. Re-checks ',
            t.code('hasAnySubscriber'),
            ' (in case a subscriber arrived during the grace window) and tears down all per-name maps + the store entry.',
          ]),
          t.li([
            t.code('hasAnySubscriber(name)'),
            '. True when ',
            t.code('subs[name]'),
            ' or ',
            t.code('nameSubscribers[name]'),
            ' has anyone. The drop scheduler and ',
            t.code('dropTransient'),
            ' itself both consult it.',
          ]),
        ]),
      ]),

      t.section({ id: 'live-server-attach' }, [
        t.h4('attach(httpServer)'),
        t.p([
          'Resolves the ',
          t.code('ws'),
          ' peer dep via ',
          t.code('createRequire'),
          ' anchored at the user\'s ',
          t.code('process.cwd()'),
          ' (so ',
          t.code('link:'),
          '-style installs find it), with a fallback to a dynamic ',
          t.code('import(\'ws\')'),
          '. Throws a clear error when neither works.',
        ]),
        t.p([
          'Constructs a ',
          t.code('new WebSocketServer({ server: httpServer, path })'),
          ', retains it on ',
          t.code('attachedWss'),
          ', and wires per-connection handlers:',
        ]),
        t.ul([
          t.li([
            t.code('sock._kensingtonAlive = true'),
            ' plus a ',
            t.code("sock.on('pong', ...)"),
            ' listener that re-flips the flag. The heartbeat below uses this.',
          ]),
          t.li([
            t.code('await onSocketOpen(sock, req)'),
            ' which runs the user\'s ',
            t.code('onConnect'),
            ' (catching throws and logging) and stores the returned ctx on the per-socket ',
            t.code('socketState'),
            '.',
          ]),
          t.li([
            t.code("sock.on('message', ...)"),
            ' delegates to ',
            t.code('onSocketMessage'),
            ', which dispatches on ',
            t.code('msg.type'),
            ' to the subscribe/unsubscribe/set handlers.',
          ]),
          t.li([
            t.code("sock.on('close', ...)"),
            ' calls ',
            t.code('handleSocketClose'),
            ' which removes the socket from every ',
            t.code('subs[name]'),
            ', schedules transient drops, runs the user\'s ',
            t.code('onSocketClose'),
            ' callback, and clears the per-socket state.',
          ]),
        ]),
        t.p([
          'Heartbeat. When ',
          t.code('heartbeatInterval !== false'),
          ', a ',
          t.code('setInterval'),
          ' walks ',
          t.code('wss.clients'),
          ' every interval. For each socket, if ',
          t.code('_kensingtonAlive === false'),
          ' (the previous ping never got a pong), ',
          t.code('terminate()'),
          ' is called. Otherwise the flag is reset to false and a ',
          t.code('sock.ping()'),
          ' is sent. The pong listener flips the flag back to true. The interval is ',
          t.code('unref()'),
          '-ed.',
        ]),
        callout('note', 'Bun attach mode',
          t.p([
            t.code('bunWebsocket()'),
            ' returns the ',
            t.code('{ open, message, close }'),
            ' handler config the user spreads into ',
            t.code('Bun.serve({ websocket })'),
            '. There is no ',
            t.code('attachedWss'),
            ' on this path; Bun owns the socket lifecycle through the user\'s server handle. The heartbeat is also a no-op on this path; configure Bun\'s native ',
            t.code('idleTimeout'),
            ' and ',
            t.code('sendPings'),
            ' to get the equivalent.',
          ]),
        ),
      ]),

      t.section({ id: 'live-server-handle-api' }, [
        t.h4('LiveServer handle. get / set / list / delete'),
        t.ul([
          t.li([t.code('get(name)'), '. ', t.code('registry.get(name)?.value'), '.']),
          t.li([
            t.code('set(name, value, options)'),
            '. Calls ',
            t.code('recordPersist'),
            ' then ',
            t.code('applySet(name, value, null)'),
            '. Server-side writes bypass ',
            t.code('canWrite'),
            '.',
          ]),
          t.li([
            t.code('list(prefix)'),
            '. Walks the in-memory ',
            t.code('registry'),
            ' (NOT the persistence store) and returns ',
            t.code('[[name, value], ...]'),
            ' for every name starting with the prefix. Transient entries are visible.',
          ]),
          t.li([
            t.code('delete(name)'),
            '. Cancels the transient drop, deletes from every map, and drops the cached server Signal. ',
            t.strong('Does not notify subscribers.'),
            ' Use ',
            t.code('set(name, null)'),
            ' instead when subscribers must observe the removal.',
          ]),
        ]),
      ]),

      t.section({ id: 'live-server-side-signal' }, [
        t.h4('Server-side liveSignal. makeServerSignal'),
        t.p([
          'When ',
          t.code('liveSignal(initial, name)'),
          ' runs on the server (via ',
          t.code('serverTransport.getOrCreateSignal'),
          '), it returns a long-lived Signal cached in ',
          t.code('serverSignals'),
          '. The Signal is built by ',
          t.code('makeServerSignal'),
          ', which wraps ',
          t.code('sig.set'),
          ' so writes go through ',
          t.code('applySet'),
          ' (registry + broadcast + observer notification), and registers a ',
          t.code('cb => sig._setFromRemote(value)'),
          ' observer in ',
          t.code('nameSubscribers[name]'),
          '. The cb makes the local Signal mirror client and server-initiated writes; ',
          t.code('_setFromRemote'),
          ' short-circuits when the value already matches, so the writer\'s own callback does not double-notify its subscribers.',
        ]),
        t.p([
          'Calling ',
          t.code('sig.stop()'),
          ' removes the cb, drops the cache entry, and (if the observer set is now empty) triggers ',
          t.code('scheduleTransientDropIfNeeded(name)'),
          '.',
        ]),
      ]),

      t.section({ id: 'live-server-close' }, [
        t.h4('close()'),
        t.p([
          'Tears down the WebSocket server first to stop in-flight broadcasts from racing on a half-closed socket. For each ',
          t.code('attachedWss.clients'),
          ' calls ',
          t.code('terminate()'),
          ' (skipping the close-handshake wait), then ',
          t.code('wss.close()'),
          '. Clears the heartbeat interval. Drops every transient-drop timer. Clears ',
          t.code('nameSubscribers'),
          ' and ',
          t.code('serverSignals'),
          '. Closes the persistence store.',
        ]),
      ]),
    ]),

    t.section({ id: 'live-persistence' }, [
      t.h3('Persistence adapters'),
      t.p([
        'Both adapters expose ',
        t.code('get(name)'),
        ', ',
        t.code('set(name, value)'),
        ', ',
        t.code('delete(name)'),
        ', ',
        t.code('all()'),
        ', and ',
        t.code('close()'),
        '. The server warms the in-memory registry from ',
        t.code('store.all()'),
        ' at boot.',
      ]),
      t.ul([
        t.li([
          loc('esm/live/persistence/memory.js'),
          '. ',
          t.code('Map'),
          '-backed. Synchronous. Default backend.',
        ]),
        t.li([
          loc('esm/live/persistence/sqlite.js'),
          '. Lazy-loads ',
          t.code('better-sqlite3'),
          ' via ',
          t.code('createRequire'),
          ' anchored at the user\'s ',
          t.code('cwd'),
          '. Maintains an in-memory mirror so reads stay sync. Writes are debounced via ',
          t.code('setTimeout'),
          ' (default 250ms) and grouped into a single transaction; the flush is ',
          t.code('unref()'),
          '-ed so a pending debounce never pins the event loop.',
        ]),
      ]),
    ]),

    t.section({ id: 'live-cheatsheet' }, [
      t.h3('Where to look'),
      t.table([
        t.thead(t.tr([
          t.th({ style: { width: '20em' } }, "If you're working on..."),
          t.th('Look at...'),
        ])),
        t.tbody([
          t.tr([
            t.td('Wire format, message types, encode/decode'),
            t.td(loc('esm/live/protocol.js')),
          ]),
          t.tr([
            t.td('The no-transport fallback or the liveSignal factory'),
            t.td(loc('esm/live/state.js')),
          ]),
          t.tr([
            t.td('Reconnect backoff, CAS retry, frame inspection'),
            t.td([
              loc('esm/live/client.js'),
              '. ',
              t.code('scheduleReconnect'),
              ', ',
              t.code('retryCas'),
              ', ',
              t.code('notifyFrame'),
              '.',
            ]),
          ]),
          t.tr([
            t.td('canWrite enforcement, CAS check, write commit'),
            t.td([loc('esm/live/server.js'), '. ', t.code('handleClientSet'), ' + ', t.code('commitWrite'), '.']),
          ]),
          t.tr([
            t.td('Broadcast batching, batch-update grouping'),
            t.td([loc('esm/live/server.js'), '. ', t.code('broadcast'), ' + ', t.code('flushBroadcasts'), '.']),
          ]),
          t.tr([
            t.td('Transient-drop grace period'),
            t.td([
              loc('esm/live/server.js'),
              '. ',
              t.code('scheduleTransientDropIfNeeded'),
              ', ',
              t.code('dropTransient'),
              ', ',
              t.code('TRANSIENT_GRACE_MS'),
              '.',
            ]),
          ]),
          t.tr([
            t.td('Heartbeat / dead-socket detection'),
            t.td([
              loc('esm/live/server.js'),
              '. The ',
              t.code('setInterval'),
              ' inside ',
              t.code('attach()'),
              ' plus the per-socket ',
              t.code('_kensingtonAlive'),
              ' flag.',
            ]),
          ]),
          t.tr([
            t.td('Server-side liveSignal as a reactive subscription'),
            t.td([
              loc('esm/live/server.js'),
              '. ',
              t.code('makeServerSignal'),
              ' + ',
              t.code('serverTransport.getOrCreateSignal'),
              '.',
            ]),
          ]),
          t.tr([
            t.td('Sqlite persistence and the debounced flush'),
            t.td(loc('esm/live/persistence/sqlite.js')),
          ]),
        ]),
      ]),
    ]),
  ]);
}
