import { callout, code } from '../../components/ui.js';
import { loc, mermaid } from './helpers.js';

export function architecturePipeline(t) {
  return t.section({ id: 'pipeline' }, [
    t.h2('The Pipeline'),
    t.p([
      'Kensington has two output modes from one tag instance. The same ',
      t.code('ContentTag'),
      ' object can produce an HTML string via ',
      t.code('toString'),
      ' or a live DOM tree via ',
      t.code('toElement'),
      '. The pipelines diverge only at the rendering stage.',
    ]),
    mermaid(t, `flowchart TD
  A["t.div(attrs, content)"] --> B["createTag closure"]
  B --> C["new ContentTag(options)"]
  C --> D["collectContent: flatten arrays, drop falsy"]
  D --> E{"validationLevel != 'off'?"}
  E -- yes --> F["validate(tag)"]
  E -- no --> G["tag instance returned"]
  F --> G
  G --> H{"User calls..."}
  H -- "toString()" --> I["renderToString"]
  H -- "toElement()" --> J["DOM build + Lifecycle"]
  I --> K["HTML string"]
  J --> L["Live element"]`),
    t.p([
      t.code('t'),
      ' is an instance of the generated ',
      t.code('Kensington'),
      ' class at ',
      loc(t, 'esm/kensington.js'),
      '. Every tag method (',
      t.code('t.div'),
      ', ',
      t.code('t.span'),
      ', etc.) is a closure produced by ',
      t.code('createTag'),
      '. The closure captures the tag name, the allowed-attribute spec map, the ',
      t.code('Klass'),
      ' (which subclass to instantiate), and per-tag options like ',
      t.code('namespace'),
      ' or ',
      t.code('contentIsLiteral'),
      '.',
    ]),
    callout(t, 'note', 'Generated file',
      t.p([
        t.code('esm/kensington.js'),
        ' is generated by ',
        loc(t, 'generate/bin/write-code-files.js'),
        ' from spec data. Do not edit it directly. All hand-written source lives in ',
        loc(t, 'esm/tag-classes/'),
        ' and ',
        loc(t, 'esm/lib/'),
        '.',
      ]),
    ),
  ]);
}
