'use strict';

const globalAttributes = {
  'accesskey': String,
  'autocapitalize': ["on","off","none","sentences","words","characters"],
  'autocorrect': ["on","off"],
  'autofocus': Boolean,
  'class': String,
  'contenteditable': ["true","plaintext-only","false"],
  'dir': ["ltr","LTR","rtl","RTL","auto","AUTO"],
  'draggable': ["true","false"],
  'enterkeyhint': ["enter","done","go","next","previous","search","send"],
  'hidden': String,
  'id': String,
  'inert': Boolean,
  'inputmode': ["none","text","tel","email","url","numeric","decimal","search"],
  'is': String,
  'itemid': String,
  'itemprop': String,
  'itemref': String,
  'itemscope': Boolean,
  'itemtype': String,
  'lang': String,
  'nonce': String,
  'popover': ["auto","manual","hint"],
  'role': String,
  'slot': String,
  'spellcheck': String,
  'style': String,
  'tabindex': String,
  'title': String,
  'translate': ["yes","no"],
  'writingsuggestions': String,
};
  
const globalEvents = {
  'onauxclick': String,
  'onbeforeinput': String,
  'onbeforematch': String,
  'onbeforetoggle': String,
  'onblur': String,
  'oncancel': String,
  'oncanplay': String,
  'oncanplaythrough': String,
  'onchange': String,
  'onclick': String,
  'onclose': String,
  'oncommand': String,
  'oncontextlost': String,
  'oncontextmenu': String,
  'oncontextrestored': String,
  'oncopy': String,
  'oncuechange': String,
  'oncut': String,
  'ondblclick': String,
  'ondrag': String,
  'ondragend': String,
  'ondragenter': String,
  'ondragleave': String,
  'ondragover': String,
  'ondragstart': String,
  'ondrop': String,
  'ondurationchange': String,
  'onemptied': String,
  'onended': String,
  'onerror': String,
  'onfocus': String,
  'onformdata': String,
  'oninput': String,
  'oninvalid': String,
  'onkeydown': String,
  'onkeypress': String,
  'onkeyup': String,
  'onload': String,
  'onloadeddata': String,
  'onloadedmetadata': String,
  'onloadstart': String,
  'onmousedown': String,
  'onmouseenter': String,
  'onmouseleave': String,
  'onmousemove': String,
  'onmouseout': String,
  'onmouseover': String,
  'onmouseup': String,
  'onpaste': String,
  'onpause': String,
  'onplay': String,
  'onplaying': String,
  'onprogress': String,
  'onratechange': String,
  'onreset': String,
  'onresize': String,
  'onscroll': String,
  'onscrollend': String,
  'onsecuritypolicyviolation': String,
  'onseeked': String,
  'onseeking': String,
  'onselect': String,
  'onslotchange': String,
  'onstalled': String,
  'onsubmit': String,
  'onsuspend': String,
  'ontimeupdate': String,
  'ontoggle': String,
  'onvolumechange': String,
  'onwaiting': String,
  'onwheel': String,
};

const aAttributes = {
  'download': String,
  'href': String,
  'hreflang': String,
  'ping': String,
  'referrerpolicy': String,
  'rel': String,
  'target': String,
  'type': String
};
const abbrAttributes = {};
const addressAttributes = {};
const animateAttributes = {
  'accumulate': ["none","sum"],
  'additive': ["replace","sum"],
  'attributeName': String,
  'autofocus': Boolean,
  'begin': String,
  'by': String,
  'calcMode': ["discrete","linear","paced","spline"],
  'class': String,
  'dur': String,
  'end': String,
  'fill': ["remove","freeze"],
  'from': String,
  'href': String,
  'id': String,
  'keySplines': String,
  'keyTimes': String,
  'lang': String,
  'max': String,
  'min': String,
  'onbegin': String,
  'oncancel': String,
  'oncanplay': String,
  'oncanplaythrough': String,
  'onchange': String,
  'onclick': String,
  'onclose': String,
  'oncopy': String,
  'oncuechange': String,
  'oncut': String,
  'ondblclick': String,
  'ondrag': String,
  'ondragend': String,
  'ondragenter': String,
  'ondragexit': String,
  'ondragleave': String,
  'ondragover': String,
  'ondragstart': String,
  'ondrop': String,
  'ondurationchange': String,
  'onemptied': String,
  'onend': String,
  'onended': String,
  'onerror': String,
  'onfocus': String,
  'oninput': String,
  'oninvalid': String,
  'onkeydown': String,
  'onkeypress': String,
  'onkeyup': String,
  'onload': String,
  'onloadeddata': String,
  'onloadedmetadata': String,
  'onloadstart': String,
  'onmousedown': String,
  'onmouseenter': String,
  'onmouseleave': String,
  'onmousemove': String,
  'onmouseout': String,
  'onmouseover': String,
  'onmouseup': String,
  'onpaste': String,
  'onpause': String,
  'onplay': String,
  'onplaying': String,
  'onprogress': String,
  'onratechange': String,
  'onrepeat': String,
  'onreset': String,
  'onresize': String,
  'onscroll': String,
  'onseeked': String,
  'onseeking': String,
  'onselect': String,
  'onshow': String,
  'onstalled': String,
  'onsubmit': String,
  'onsuspend': String,
  'ontimeupdate': String,
  'ontoggle': String,
  'onvolumechange': String,
  'onwaiting': String,
  'onwheel': String,
  'repeatCount': String,
  'repeatDur': String,
  'requiredExtensions': String,
  'restart': ["always","never","whenNotActive"],
  'style': String,
  'systemLanguage': String,
  'tabindex': String,
  'to': String,
  'values': String,
  'xml:space': ["default","preserve"]
};
const animateMotionAttributes = {
  'accumulate': ["none","sum"],
  'additive': ["replace","sum"],
  'autofocus': Boolean,
  'begin': String,
  'by': String,
  'calcMode': ["discrete","linear","paced","spline"],
  'class': String,
  'dur': String,
  'end': String,
  'fill': ["remove","freeze"],
  'from': String,
  'href': String,
  'id': String,
  'keyPoints': String,
  'keySplines': String,
  'keyTimes': String,
  'lang': String,
  'max': String,
  'min': String,
  'onbegin': String,
  'oncancel': String,
  'oncanplay': String,
  'oncanplaythrough': String,
  'onchange': String,
  'onclick': String,
  'onclose': String,
  'oncopy': String,
  'oncuechange': String,
  'oncut': String,
  'ondblclick': String,
  'ondrag': String,
  'ondragend': String,
  'ondragenter': String,
  'ondragexit': String,
  'ondragleave': String,
  'ondragover': String,
  'ondragstart': String,
  'ondrop': String,
  'ondurationchange': String,
  'onemptied': String,
  'onend': String,
  'onended': String,
  'onerror': String,
  'onfocus': String,
  'oninput': String,
  'oninvalid': String,
  'onkeydown': String,
  'onkeypress': String,
  'onkeyup': String,
  'onload': String,
  'onloadeddata': String,
  'onloadedmetadata': String,
  'onloadstart': String,
  'onmousedown': String,
  'onmouseenter': String,
  'onmouseleave': String,
  'onmousemove': String,
  'onmouseout': String,
  'onmouseover': String,
  'onmouseup': String,
  'onpaste': String,
  'onpause': String,
  'onplay': String,
  'onplaying': String,
  'onprogress': String,
  'onratechange': String,
  'onrepeat': String,
  'onreset': String,
  'onresize': String,
  'onscroll': String,
  'onseeked': String,
  'onseeking': String,
  'onselect': String,
  'onshow': String,
  'onstalled': String,
  'onsubmit': String,
  'onsuspend': String,
  'ontimeupdate': String,
  'ontoggle': String,
  'onvolumechange': String,
  'onwaiting': String,
  'onwheel': String,
  'origin': String,
  'path': String,
  'repeatCount': String,
  'repeatDur': String,
  'requiredExtensions': String,
  'restart': ["always","never","whenNotActive"],
  'rotate': String,
  'style': String,
  'systemLanguage': String,
  'tabindex': String,
  'to': String,
  'values': String,
  'xml:space': ["default","preserve"]
};
const animateTransformAttributes = {
  'accumulate': ["none","sum"],
  'additive': ["replace","sum"],
  'attributeName': String,
  'autofocus': Boolean,
  'begin': String,
  'by': String,
  'calcMode': ["discrete","linear","paced","spline"],
  'class': String,
  'dur': String,
  'end': String,
  'fill': ["remove","freeze"],
  'from': String,
  'href': String,
  'id': String,
  'keySplines': String,
  'keyTimes': String,
  'lang': String,
  'max': String,
  'min': String,
  'onbegin': String,
  'oncancel': String,
  'oncanplay': String,
  'oncanplaythrough': String,
  'onchange': String,
  'onclick': String,
  'onclose': String,
  'oncopy': String,
  'oncuechange': String,
  'oncut': String,
  'ondblclick': String,
  'ondrag': String,
  'ondragend': String,
  'ondragenter': String,
  'ondragexit': String,
  'ondragleave': String,
  'ondragover': String,
  'ondragstart': String,
  'ondrop': String,
  'ondurationchange': String,
  'onemptied': String,
  'onend': String,
  'onended': String,
  'onerror': String,
  'onfocus': String,
  'oninput': String,
  'oninvalid': String,
  'onkeydown': String,
  'onkeypress': String,
  'onkeyup': String,
  'onload': String,
  'onloadeddata': String,
  'onloadedmetadata': String,
  'onloadstart': String,
  'onmousedown': String,
  'onmouseenter': String,
  'onmouseleave': String,
  'onmousemove': String,
  'onmouseout': String,
  'onmouseover': String,
  'onmouseup': String,
  'onpaste': String,
  'onpause': String,
  'onplay': String,
  'onplaying': String,
  'onprogress': String,
  'onratechange': String,
  'onrepeat': String,
  'onreset': String,
  'onresize': String,
  'onscroll': String,
  'onseeked': String,
  'onseeking': String,
  'onselect': String,
  'onshow': String,
  'onstalled': String,
  'onsubmit': String,
  'onsuspend': String,
  'ontimeupdate': String,
  'ontoggle': String,
  'onvolumechange': String,
  'onwaiting': String,
  'onwheel': String,
  'repeatCount': String,
  'repeatDur': String,
  'requiredExtensions': String,
  'restart': ["always","never","whenNotActive"],
  'style': String,
  'systemLanguage': String,
  'tabindex': String,
  'to': String,
  'type': ["translate","scale","rotate","skewX","skewY"],
  'values': String,
  'xml:space': ["default","preserve"]
};
const areaAttributes = {
  'alt': String,
  'coords': String,
  'download': String,
  'href': String,
  'ping': String,
  'referrerpolicy': String,
  'rel': String,
  'shape': ["circle","CIRCLE","default","DEFAULT","poly","POLY","rect","RECT"],
  'target': String
};
const articleAttributes = {};
const asideAttributes = {};
const audioAttributes = {
  'autoplay': Boolean,
  'controls': Boolean,
  'crossorigin': ["anonymous","use-credentials"],
  'loop': Boolean,
  'muted': Boolean,
  'preload': ["none","metadata","auto"],
  'src': String
};
const bAttributes = {};
const baseAttributes = {
  'href': String,
  'target': String
};
const bdiAttributes = {};
const bdoAttributes = {};
const blockquoteAttributes = {
  'cite': String
};
const bodyAttributes = {
  'onafterprint': String,
  'onbeforeprint': String,
  'onbeforeunload': String,
  'onhashchange': String,
  'onlanguagechange': String,
  'onmessage': String,
  'onmessageerror': String,
  'onoffline': String,
  'ononline': String,
  'onpagehide': String,
  'onpagereveal': String,
  'onpageshow': String,
  'onpageswap': String,
  'onpopstate': String,
  'onrejectionhandled': String,
  'onstorage': String,
  'onunhandledrejection': String,
  'onunload': String
};
const brAttributes = {};
const buttonAttributes = {
  'command': String,
  'commandfor': String,
  'disabled': Boolean,
  'form': String,
  'formaction': String,
  'formenctype': ["application/x-www-form-urlencoded","multipart/form-data","text/plain"],
  'formmethod': ["get","GET","post","POST","dialog","DIALOG"],
  'formnovalidate': Boolean,
  'formtarget': String,
  'name': String,
  'popovertarget': String,
  'popovertargetaction': ["toggle","show","hide"],
  'type': ["submit","SUBMIT","reset","RESET","button","BUTTON"],
  'value': [Number,String]
};
const canvasAttributes = {
  'height': String,
  'width': String
};
const captionAttributes = {};
const circleAttributes = {
  'autofocus': Boolean,
  'class': String,
  'cx': [Number,String],
  'cy': [Number,String],
  'id': String,
  'lang': String,
  'oncancel': String,
  'oncanplay': String,
  'oncanplaythrough': String,
  'onchange': String,
  'onclick': String,
  'onclose': String,
  'oncopy': String,
  'oncuechange': String,
  'oncut': String,
  'ondblclick': String,
  'ondrag': String,
  'ondragend': String,
  'ondragenter': String,
  'ondragexit': String,
  'ondragleave': String,
  'ondragover': String,
  'ondragstart': String,
  'ondrop': String,
  'ondurationchange': String,
  'onemptied': String,
  'onended': String,
  'onerror': String,
  'onfocus': String,
  'oninput': String,
  'oninvalid': String,
  'onkeydown': String,
  'onkeypress': String,
  'onkeyup': String,
  'onload': String,
  'onloadeddata': String,
  'onloadedmetadata': String,
  'onloadstart': String,
  'onmousedown': String,
  'onmouseenter': String,
  'onmouseleave': String,
  'onmousemove': String,
  'onmouseout': String,
  'onmouseover': String,
  'onmouseup': String,
  'onpaste': String,
  'onpause': String,
  'onplay': String,
  'onplaying': String,
  'onprogress': String,
  'onratechange': String,
  'onreset': String,
  'onresize': String,
  'onscroll': String,
  'onseeked': String,
  'onseeking': String,
  'onselect': String,
  'onshow': String,
  'onstalled': String,
  'onsubmit': String,
  'onsuspend': String,
  'ontimeupdate': String,
  'ontoggle': String,
  'onvolumechange': String,
  'onwaiting': String,
  'onwheel': String,
  'pathLength': String,
  'r': [Number,String],
  'requiredExtensions': String,
  'role': String,
  'style': String,
  'systemLanguage': String,
  'tabindex': String,
  'xml:space': ["default","preserve"]
};
const citeAttributes = {};
const clipPathAttributes = {
  'class': String,
  'externalResourcesRequired': String,
  'id': String,
  'requiredExtensions': String,
  'requiredFeatures': String,
  'style': String,
  'systemLanguage': String,
  'transform': String,
  'xml:base': String,
  'xml:lang': String,
  'xml:space': String
};
const codeAttributes = {};
const colAttributes = {
  'span': Number
};
const colgroupAttributes = {
  'span': Number
};
const dataAttributes = {
  'value': [Number,String]
};
const datalistAttributes = {};
const ddAttributes = {};
const defsAttributes = {
  'autofocus': Boolean,
  'class': String,
  'id': String,
  'lang': String,
  'oncancel': String,
  'oncanplay': String,
  'oncanplaythrough': String,
  'onchange': String,
  'onclick': String,
  'onclose': String,
  'oncopy': String,
  'oncuechange': String,
  'oncut': String,
  'ondblclick': String,
  'ondrag': String,
  'ondragend': String,
  'ondragenter': String,
  'ondragexit': String,
  'ondragleave': String,
  'ondragover': String,
  'ondragstart': String,
  'ondrop': String,
  'ondurationchange': String,
  'onemptied': String,
  'onended': String,
  'onerror': String,
  'onfocus': String,
  'oninput': String,
  'oninvalid': String,
  'onkeydown': String,
  'onkeypress': String,
  'onkeyup': String,
  'onload': String,
  'onloadeddata': String,
  'onloadedmetadata': String,
  'onloadstart': String,
  'onmousedown': String,
  'onmouseenter': String,
  'onmouseleave': String,
  'onmousemove': String,
  'onmouseout': String,
  'onmouseover': String,
  'onmouseup': String,
  'onpaste': String,
  'onpause': String,
  'onplay': String,
  'onplaying': String,
  'onprogress': String,
  'onratechange': String,
  'onreset': String,
  'onresize': String,
  'onscroll': String,
  'onseeked': String,
  'onseeking': String,
  'onselect': String,
  'onshow': String,
  'onstalled': String,
  'onsubmit': String,
  'onsuspend': String,
  'ontimeupdate': String,
  'ontoggle': String,
  'onvolumechange': String,
  'onwaiting': String,
  'onwheel': String,
  'style': String,
  'tabindex': String,
  'xml:space': ["default","preserve"]
};
const delAttributes = {
  'cite': String,
  'datetime': String
};
const descAttributes = {
  'autofocus': Boolean,
  'class': String,
  'id': String,
  'lang': String,
  'oncancel': String,
  'oncanplay': String,
  'oncanplaythrough': String,
  'onchange': String,
  'onclick': String,
  'onclose': String,
  'oncopy': String,
  'oncuechange': String,
  'oncut': String,
  'ondblclick': String,
  'ondrag': String,
  'ondragend': String,
  'ondragenter': String,
  'ondragexit': String,
  'ondragleave': String,
  'ondragover': String,
  'ondragstart': String,
  'ondrop': String,
  'ondurationchange': String,
  'onemptied': String,
  'onended': String,
  'onerror': String,
  'onfocus': String,
  'oninput': String,
  'oninvalid': String,
  'onkeydown': String,
  'onkeypress': String,
  'onkeyup': String,
  'onload': String,
  'onloadeddata': String,
  'onloadedmetadata': String,
  'onloadstart': String,
  'onmousedown': String,
  'onmouseenter': String,
  'onmouseleave': String,
  'onmousemove': String,
  'onmouseout': String,
  'onmouseover': String,
  'onmouseup': String,
  'onpaste': String,
  'onpause': String,
  'onplay': String,
  'onplaying': String,
  'onprogress': String,
  'onratechange': String,
  'onreset': String,
  'onresize': String,
  'onscroll': String,
  'onseeked': String,
  'onseeking': String,
  'onselect': String,
  'onshow': String,
  'onstalled': String,
  'onsubmit': String,
  'onsuspend': String,
  'ontimeupdate': String,
  'ontoggle': String,
  'onvolumechange': String,
  'onwaiting': String,
  'onwheel': String,
  'style': String,
  'tabindex': String,
  'xml:space': ["default","preserve"]
};
const detailsAttributes = {
  'name': String,
  'open': Boolean
};
const dfnAttributes = {};
const dialogAttributes = {
  'open': Boolean
};
const divAttributes = {};
const dlAttributes = {};
const dtAttributes = {};
const ellipseAttributes = {
  'autofocus': Boolean,
  'class': String,
  'cx': [Number,String],
  'cy': [Number,String],
  'id': String,
  'lang': String,
  'oncancel': String,
  'oncanplay': String,
  'oncanplaythrough': String,
  'onchange': String,
  'onclick': String,
  'onclose': String,
  'oncopy': String,
  'oncuechange': String,
  'oncut': String,
  'ondblclick': String,
  'ondrag': String,
  'ondragend': String,
  'ondragenter': String,
  'ondragexit': String,
  'ondragleave': String,
  'ondragover': String,
  'ondragstart': String,
  'ondrop': String,
  'ondurationchange': String,
  'onemptied': String,
  'onended': String,
  'onerror': String,
  'onfocus': String,
  'oninput': String,
  'oninvalid': String,
  'onkeydown': String,
  'onkeypress': String,
  'onkeyup': String,
  'onload': String,
  'onloadeddata': String,
  'onloadedmetadata': String,
  'onloadstart': String,
  'onmousedown': String,
  'onmouseenter': String,
  'onmouseleave': String,
  'onmousemove': String,
  'onmouseout': String,
  'onmouseover': String,
  'onmouseup': String,
  'onpaste': String,
  'onpause': String,
  'onplay': String,
  'onplaying': String,
  'onprogress': String,
  'onratechange': String,
  'onreset': String,
  'onresize': String,
  'onscroll': String,
  'onseeked': String,
  'onseeking': String,
  'onselect': String,
  'onshow': String,
  'onstalled': String,
  'onsubmit': String,
  'onsuspend': String,
  'ontimeupdate': String,
  'ontoggle': String,
  'onvolumechange': String,
  'onwaiting': String,
  'onwheel': String,
  'pathLength': String,
  'requiredExtensions': String,
  'role': String,
  'rx': [Number,String],
  'ry': [Number,String],
  'style': String,
  'systemLanguage': String,
  'tabindex': String,
  'xml:space': ["default","preserve"]
};
const emAttributes = {};
const embedAttributes = {
  'height': String,
  'src': String,
  'type': String,
  'width': String
};
const fieldsetAttributes = {
  'disabled': Boolean,
  'form': String,
  'name': String
};
const figcaptionAttributes = {};
const figureAttributes = {};
const footerAttributes = {};
const foreignObjectAttributes = {
  'autofocus': Boolean,
  'class': String,
  'height': [Number,String],
  'id': String,
  'lang': String,
  'oncancel': String,
  'oncanplay': String,
  'oncanplaythrough': String,
  'onchange': String,
  'onclick': String,
  'onclose': String,
  'oncopy': String,
  'oncuechange': String,
  'oncut': String,
  'ondblclick': String,
  'ondrag': String,
  'ondragend': String,
  'ondragenter': String,
  'ondragexit': String,
  'ondragleave': String,
  'ondragover': String,
  'ondragstart': String,
  'ondrop': String,
  'ondurationchange': String,
  'onemptied': String,
  'onended': String,
  'onerror': String,
  'onfocus': String,
  'oninput': String,
  'oninvalid': String,
  'onkeydown': String,
  'onkeypress': String,
  'onkeyup': String,
  'onload': String,
  'onloadeddata': String,
  'onloadedmetadata': String,
  'onloadstart': String,
  'onmousedown': String,
  'onmouseenter': String,
  'onmouseleave': String,
  'onmousemove': String,
  'onmouseout': String,
  'onmouseover': String,
  'onmouseup': String,
  'onpaste': String,
  'onpause': String,
  'onplay': String,
  'onplaying': String,
  'onprogress': String,
  'onratechange': String,
  'onreset': String,
  'onresize': String,
  'onscroll': String,
  'onseeked': String,
  'onseeking': String,
  'onselect': String,
  'onshow': String,
  'onstalled': String,
  'onsubmit': String,
  'onsuspend': String,
  'ontimeupdate': String,
  'ontoggle': String,
  'onvolumechange': String,
  'onwaiting': String,
  'onwheel': String,
  'requiredExtensions': String,
  'role': String,
  'style': String,
  'systemLanguage': String,
  'tabindex': String,
  'width': [Number,String],
  'x': [Number,String],
  'xml:space': ["default","preserve"],
  'y': [Number,String]
};
const formAttributes = {
  'accept-charset': String,
  'action': String,
  'autocomplete': ["on","off"],
  'enctype': ["application/x-www-form-urlencoded","APPLICATION/X-WWW-FORM-URLENCODED","multipart/form-data","MULTIPART/FORM-DATA","text/plain","TEXT/PLAIN"],
  'method': ["get","GET","post","POST","dialog","DIALOG"],
  'name': String,
  'novalidate': Boolean,
  'rel': String,
  'target': String
};
const gAttributes = {
  'autofocus': Boolean,
  'class': String,
  'id': String,
  'lang': String,
  'oncancel': String,
  'oncanplay': String,
  'oncanplaythrough': String,
  'onchange': String,
  'onclick': String,
  'onclose': String,
  'oncopy': String,
  'oncuechange': String,
  'oncut': String,
  'ondblclick': String,
  'ondrag': String,
  'ondragend': String,
  'ondragenter': String,
  'ondragexit': String,
  'ondragleave': String,
  'ondragover': String,
  'ondragstart': String,
  'ondrop': String,
  'ondurationchange': String,
  'onemptied': String,
  'onended': String,
  'onerror': String,
  'onfocus': String,
  'oninput': String,
  'oninvalid': String,
  'onkeydown': String,
  'onkeypress': String,
  'onkeyup': String,
  'onload': String,
  'onloadeddata': String,
  'onloadedmetadata': String,
  'onloadstart': String,
  'onmousedown': String,
  'onmouseenter': String,
  'onmouseleave': String,
  'onmousemove': String,
  'onmouseout': String,
  'onmouseover': String,
  'onmouseup': String,
  'onpaste': String,
  'onpause': String,
  'onplay': String,
  'onplaying': String,
  'onprogress': String,
  'onratechange': String,
  'onreset': String,
  'onresize': String,
  'onscroll': String,
  'onseeked': String,
  'onseeking': String,
  'onselect': String,
  'onshow': String,
  'onstalled': String,
  'onsubmit': String,
  'onsuspend': String,
  'ontimeupdate': String,
  'ontoggle': String,
  'onvolumechange': String,
  'onwaiting': String,
  'onwheel': String,
  'requiredExtensions': String,
  'role': String,
  'style': String,
  'systemLanguage': String,
  'tabindex': String,
  'xml:space': ["default","preserve"]
};
const h1Attributes = {};
const h2Attributes = {};
const h3Attributes = {};
const h4Attributes = {};
const h5Attributes = {};
const h6Attributes = {};
const headAttributes = {};
const headerAttributes = {};
const hgroupAttributes = {};
const hrAttributes = {};
const htmlAttributes = {};
const iAttributes = {};
const iframeAttributes = {
  'allow': String,
  'allowfullscreen': Boolean,
  'height': String,
  'loading': ["lazy","eager"],
  'name': String,
  'referrerpolicy': String,
  'sandbox': String,
  'src': String,
  'srcdoc': String,
  'width': String
};
const imageAttributes = {
  'autofocus': Boolean,
  'class': String,
  'crossorigin': String,
  'height': [Number,String],
  'href': String,
  'id': String,
  'lang': String,
  'oncancel': String,
  'oncanplay': String,
  'oncanplaythrough': String,
  'onchange': String,
  'onclick': String,
  'onclose': String,
  'oncopy': String,
  'oncuechange': String,
  'oncut': String,
  'ondblclick': String,
  'ondrag': String,
  'ondragend': String,
  'ondragenter': String,
  'ondragexit': String,
  'ondragleave': String,
  'ondragover': String,
  'ondragstart': String,
  'ondrop': String,
  'ondurationchange': String,
  'onemptied': String,
  'onended': String,
  'onerror': String,
  'onfocus': String,
  'oninput': String,
  'oninvalid': String,
  'onkeydown': String,
  'onkeypress': String,
  'onkeyup': String,
  'onload': String,
  'onloadeddata': String,
  'onloadedmetadata': String,
  'onloadstart': String,
  'onmousedown': String,
  'onmouseenter': String,
  'onmouseleave': String,
  'onmousemove': String,
  'onmouseout': String,
  'onmouseover': String,
  'onmouseup': String,
  'onpaste': String,
  'onpause': String,
  'onplay': String,
  'onplaying': String,
  'onprogress': String,
  'onratechange': String,
  'onreset': String,
  'onresize': String,
  'onscroll': String,
  'onseeked': String,
  'onseeking': String,
  'onselect': String,
  'onshow': String,
  'onstalled': String,
  'onsubmit': String,
  'onsuspend': String,
  'ontimeupdate': String,
  'ontoggle': String,
  'onvolumechange': String,
  'onwaiting': String,
  'onwheel': String,
  'preserveAspectRatio': String,
  'requiredExtensions': String,
  'role': String,
  'style': String,
  'systemLanguage': String,
  'tabindex': String,
  'width': [Number,String],
  'x': [Number,String],
  'xlink:href': String,
  'xlink:title': String,
  'xml:space': ["default","preserve"],
  'y': [Number,String]
};
const imgAttributes = {
  'alt': String,
  'crossorigin': ["anonymous","use-credentials"],
  'decoding': ["sync","async","auto"],
  'fetchpriority': ["auto","high","low"],
  'height': String,
  'ismap': Boolean,
  'loading': ["lazy","eager"],
  'referrerpolicy': String,
  'sizes': String,
  'src': String,
  'srcset': String,
  'usemap': String,
  'width': String
};
const inputAttributes = {
  'accept': String,
  'alpha': Boolean,
  'alt': String,
  'autocomplete': String,
  'checked': Boolean,
  'colorspace': ["limited-srgb","display-p3"],
  'dirname': String,
  'disabled': Boolean,
  'form': String,
  'formaction': String,
  'formenctype': ["application/x-www-form-urlencoded","multipart/form-data","text/plain"],
  'formmethod': ["get","GET","post","POST","dialog","DIALOG"],
  'formnovalidate': Boolean,
  'formtarget': String,
  'height': String,
  'list': String,
  'max': String,
  'maxlength': String,
  'min': String,
  'minlength': String,
  'multiple': Boolean,
  'name': String,
  'pattern': String,
  'placeholder': String,
  'popovertarget': String,
  'popovertargetaction': ["toggle","show","hide"],
  'readonly': Boolean,
  'required': Boolean,
  'size': Number,
  'src': String,
  'step': String,
  'type': String,
  'value': [Number,String],
  'width': String
};
const insAttributes = {
  'cite': String,
  'datetime': String
};
const kbdAttributes = {};
const labelAttributes = {
  'for': String
};
const legendAttributes = {};
const liAttributes = {
  'value*': String
};
const lineAttributes = {
  'autofocus': Boolean,
  'class': String,
  'id': String,
  'lang': String,
  'oncancel': String,
  'oncanplay': String,
  'oncanplaythrough': String,
  'onchange': String,
  'onclick': String,
  'onclose': String,
  'oncopy': String,
  'oncuechange': String,
  'oncut': String,
  'ondblclick': String,
  'ondrag': String,
  'ondragend': String,
  'ondragenter': String,
  'ondragexit': String,
  'ondragleave': String,
  'ondragover': String,
  'ondragstart': String,
  'ondrop': String,
  'ondurationchange': String,
  'onemptied': String,
  'onended': String,
  'onerror': String,
  'onfocus': String,
  'oninput': String,
  'oninvalid': String,
  'onkeydown': String,
  'onkeypress': String,
  'onkeyup': String,
  'onload': String,
  'onloadeddata': String,
  'onloadedmetadata': String,
  'onloadstart': String,
  'onmousedown': String,
  'onmouseenter': String,
  'onmouseleave': String,
  'onmousemove': String,
  'onmouseout': String,
  'onmouseover': String,
  'onmouseup': String,
  'onpaste': String,
  'onpause': String,
  'onplay': String,
  'onplaying': String,
  'onprogress': String,
  'onratechange': String,
  'onreset': String,
  'onresize': String,
  'onscroll': String,
  'onseeked': String,
  'onseeking': String,
  'onselect': String,
  'onshow': String,
  'onstalled': String,
  'onsubmit': String,
  'onsuspend': String,
  'ontimeupdate': String,
  'ontoggle': String,
  'onvolumechange': String,
  'onwaiting': String,
  'onwheel': String,
  'pathLength': String,
  'requiredExtensions': String,
  'role': String,
  'style': String,
  'systemLanguage': String,
  'tabindex': String,
  'x1': [Number,String],
  'x2': [Number,String],
  'xml:space': ["default","preserve"],
  'y1': [Number,String],
  'y2': [Number,String]
};
const linearGradientAttributes = {
  'autofocus': Boolean,
  'class': String,
  'gradientTransform': String,
  'gradientUnits': ["userSpaceOnUse","objectBoundingBox"],
  'href': String,
  'id': String,
  'lang': String,
  'oncancel': String,
  'oncanplay': String,
  'oncanplaythrough': String,
  'onchange': String,
  'onclick': String,
  'onclose': String,
  'oncopy': String,
  'oncuechange': String,
  'oncut': String,
  'ondblclick': String,
  'ondrag': String,
  'ondragend': String,
  'ondragenter': String,
  'ondragexit': String,
  'ondragleave': String,
  'ondragover': String,
  'ondragstart': String,
  'ondrop': String,
  'ondurationchange': String,
  'onemptied': String,
  'onended': String,
  'onerror': String,
  'onfocus': String,
  'oninput': String,
  'oninvalid': String,
  'onkeydown': String,
  'onkeypress': String,
  'onkeyup': String,
  'onload': String,
  'onloadeddata': String,
  'onloadedmetadata': String,
  'onloadstart': String,
  'onmousedown': String,
  'onmouseenter': String,
  'onmouseleave': String,
  'onmousemove': String,
  'onmouseout': String,
  'onmouseover': String,
  'onmouseup': String,
  'onpaste': String,
  'onpause': String,
  'onplay': String,
  'onplaying': String,
  'onprogress': String,
  'onratechange': String,
  'onreset': String,
  'onresize': String,
  'onscroll': String,
  'onseeked': String,
  'onseeking': String,
  'onselect': String,
  'onshow': String,
  'onstalled': String,
  'onsubmit': String,
  'onsuspend': String,
  'ontimeupdate': String,
  'ontoggle': String,
  'onvolumechange': String,
  'onwaiting': String,
  'onwheel': String,
  'spreadMethod': String,
  'style': String,
  'tabindex': String,
  'x1': [Number,String],
  'x2': [Number,String],
  'xlink:href': String,
  'xlink:title': String,
  'xml:space': ["default","preserve"],
  'y1': [Number,String],
  'y2': [Number,String]
};
const linkAttributes = {
  'as': String,
  'blocking': String,
  'color': String,
  'crossorigin': ["anonymous","use-credentials"],
  'disabled': Boolean,
  'fetchpriority': ["auto","high","low"],
  'href': String,
  'hreflang': String,
  'imagesizes': String,
  'imagesrcset': String,
  'integrity': String,
  'media': String,
  'referrerpolicy': String,
  'rel': String,
  'sizes': String,
  'type': String
};
const mainAttributes = {};
const mapAttributes = {
  'name': String
};
const markAttributes = {};
const markerAttributes = {
  'autofocus': Boolean,
  'class': String,
  'id': String,
  'lang': String,
  'markerHeight': String,
  'markerUnits': String,
  'markerWidth': String,
  'oncancel': String,
  'oncanplay': String,
  'oncanplaythrough': String,
  'onchange': String,
  'onclick': String,
  'onclose': String,
  'oncopy': String,
  'oncuechange': String,
  'oncut': String,
  'ondblclick': String,
  'ondrag': String,
  'ondragend': String,
  'ondragenter': String,
  'ondragexit': String,
  'ondragleave': String,
  'ondragover': String,
  'ondragstart': String,
  'ondrop': String,
  'ondurationchange': String,
  'onemptied': String,
  'onended': String,
  'onerror': String,
  'onfocus': String,
  'oninput': String,
  'oninvalid': String,
  'onkeydown': String,
  'onkeypress': String,
  'onkeyup': String,
  'onload': String,
  'onloadeddata': String,
  'onloadedmetadata': String,
  'onloadstart': String,
  'onmousedown': String,
  'onmouseenter': String,
  'onmouseleave': String,
  'onmousemove': String,
  'onmouseout': String,
  'onmouseover': String,
  'onmouseup': String,
  'onpaste': String,
  'onpause': String,
  'onplay': String,
  'onplaying': String,
  'onprogress': String,
  'onratechange': String,
  'onreset': String,
  'onresize': String,
  'onscroll': String,
  'onseeked': String,
  'onseeking': String,
  'onselect': String,
  'onshow': String,
  'onstalled': String,
  'onsubmit': String,
  'onsuspend': String,
  'ontimeupdate': String,
  'ontoggle': String,
  'onvolumechange': String,
  'onwaiting': String,
  'onwheel': String,
  'orient': String,
  'preserveAspectRatio': String,
  'refX': String,
  'refY': String,
  'style': String,
  'tabindex': String,
  'viewBox': String,
  'xml:space': String
};
const maskAttributes = {
  'class': String,
  'id': String,
  'requiredExtensions': String,
  'requiredFeatures': String,
  'style': String,
  'systemLanguage': String,
  'xml:base': String,
  'xml:lang': String,
  'xml:space': String
};
const menuAttributes = {};
const metaAttributes = {
  'charset': ["utf-8","UTF-8"],
  'content': String,
  'http-equiv': ["content-type","CONTENT-TYPE","default-style","DEFAULT-STYLE","refresh","REFRESH","x-ua-compatible","X-UA-COMPATIBLE","content-security-policy","CONTENT-SECURITY-POLICY"],
  'media': String,
  'name': String
};
const metadataAttributes = {
  'autofocus': Boolean,
  'class': String,
  'id': String,
  'lang': String,
  'oncancel': String,
  'oncanplay': String,
  'oncanplaythrough': String,
  'onchange': String,
  'onclick': String,
  'onclose': String,
  'oncopy': String,
  'oncuechange': String,
  'oncut': String,
  'ondblclick': String,
  'ondrag': String,
  'ondragend': String,
  'ondragenter': String,
  'ondragexit': String,
  'ondragleave': String,
  'ondragover': String,
  'ondragstart': String,
  'ondrop': String,
  'ondurationchange': String,
  'onemptied': String,
  'onended': String,
  'onerror': String,
  'onfocus': String,
  'oninput': String,
  'oninvalid': String,
  'onkeydown': String,
  'onkeypress': String,
  'onkeyup': String,
  'onload': String,
  'onloadeddata': String,
  'onloadedmetadata': String,
  'onloadstart': String,
  'onmousedown': String,
  'onmouseenter': String,
  'onmouseleave': String,
  'onmousemove': String,
  'onmouseout': String,
  'onmouseover': String,
  'onmouseup': String,
  'onpaste': String,
  'onpause': String,
  'onplay': String,
  'onplaying': String,
  'onprogress': String,
  'onratechange': String,
  'onreset': String,
  'onresize': String,
  'onscroll': String,
  'onseeked': String,
  'onseeking': String,
  'onselect': String,
  'onshow': String,
  'onstalled': String,
  'onsubmit': String,
  'onsuspend': String,
  'ontimeupdate': String,
  'ontoggle': String,
  'onvolumechange': String,
  'onwaiting': String,
  'onwheel': String,
  'style': String,
  'tabindex': String,
  'xml:space': ["default","preserve"]
};
const meterAttributes = {
  'high': String,
  'low': String,
  'max': String,
  'min': String,
  'optimum': String,
  'value': [Number,String]
};
const mpathAttributes = {
  'autofocus': Boolean,
  'class': String,
  'href': String,
  'id': String,
  'lang': String,
  'oncancel': String,
  'oncanplay': String,
  'oncanplaythrough': String,
  'onchange': String,
  'onclick': String,
  'onclose': String,
  'oncopy': String,
  'oncuechange': String,
  'oncut': String,
  'ondblclick': String,
  'ondrag': String,
  'ondragend': String,
  'ondragenter': String,
  'ondragexit': String,
  'ondragleave': String,
  'ondragover': String,
  'ondragstart': String,
  'ondrop': String,
  'ondurationchange': String,
  'onemptied': String,
  'onended': String,
  'onerror': String,
  'onfocus': String,
  'oninput': String,
  'oninvalid': String,
  'onkeydown': String,
  'onkeypress': String,
  'onkeyup': String,
  'onload': String,
  'onloadeddata': String,
  'onloadedmetadata': String,
  'onloadstart': String,
  'onmousedown': String,
  'onmouseenter': String,
  'onmouseleave': String,
  'onmousemove': String,
  'onmouseout': String,
  'onmouseover': String,
  'onmouseup': String,
  'onpaste': String,
  'onpause': String,
  'onplay': String,
  'onplaying': String,
  'onprogress': String,
  'onratechange': String,
  'onreset': String,
  'onresize': String,
  'onscroll': String,
  'onseeked': String,
  'onseeking': String,
  'onselect': String,
  'onshow': String,
  'onstalled': String,
  'onsubmit': String,
  'onsuspend': String,
  'ontimeupdate': String,
  'ontoggle': String,
  'onvolumechange': String,
  'onwaiting': String,
  'onwheel': String,
  'style': String,
  'tabindex': String,
  'xml:space': ["default","preserve"]
};
const navAttributes = {};
const noscriptAttributes = {};
const objectAttributes = {
  'data': String,
  'form': String,
  'height': String,
  'name': String,
  'type': String,
  'width': String
};
const olAttributes = {
  'reversed': Boolean,
  'start': String,
  'type': ["1","a","A","i","I"]
};
const optgroupAttributes = {
  'disabled': Boolean,
  'label': String
};
const optionAttributes = {
  'disabled': Boolean,
  'label': String,
  'selected': Boolean,
  'value': [Number,String]
};
const outputAttributes = {
  'for': String,
  'form': String,
  'name': String
};
const pAttributes = {};
const pathAttributes = {
  'autofocus': Boolean,
  'class': String,
  'd': String,
  'id': String,
  'lang': String,
  'oncancel': String,
  'oncanplay': String,
  'oncanplaythrough': String,
  'onchange': String,
  'onclick': String,
  'onclose': String,
  'oncopy': String,
  'oncuechange': String,
  'oncut': String,
  'ondblclick': String,
  'ondrag': String,
  'ondragend': String,
  'ondragenter': String,
  'ondragexit': String,
  'ondragleave': String,
  'ondragover': String,
  'ondragstart': String,
  'ondrop': String,
  'ondurationchange': String,
  'onemptied': String,
  'onended': String,
  'onerror': String,
  'onfocus': String,
  'oninput': String,
  'oninvalid': String,
  'onkeydown': String,
  'onkeypress': String,
  'onkeyup': String,
  'onload': String,
  'onloadeddata': String,
  'onloadedmetadata': String,
  'onloadstart': String,
  'onmousedown': String,
  'onmouseenter': String,
  'onmouseleave': String,
  'onmousemove': String,
  'onmouseout': String,
  'onmouseover': String,
  'onmouseup': String,
  'onpaste': String,
  'onpause': String,
  'onplay': String,
  'onplaying': String,
  'onprogress': String,
  'onratechange': String,
  'onreset': String,
  'onresize': String,
  'onscroll': String,
  'onseeked': String,
  'onseeking': String,
  'onselect': String,
  'onshow': String,
  'onstalled': String,
  'onsubmit': String,
  'onsuspend': String,
  'ontimeupdate': String,
  'ontoggle': String,
  'onvolumechange': String,
  'onwaiting': String,
  'onwheel': String,
  'pathLength': Number,
  'requiredExtensions': String,
  'role': String,
  'style': String,
  'systemLanguage': String,
  'tabindex': String,
  'xml:space': ["default","preserve"]
};
const patternAttributes = {
  'autofocus': Boolean,
  'class': String,
  'height': String,
  'href': String,
  'id': String,
  'lang': String,
  'oncancel': String,
  'oncanplay': String,
  'oncanplaythrough': String,
  'onchange': String,
  'onclick': String,
  'onclose': String,
  'oncopy': String,
  'oncuechange': String,
  'oncut': String,
  'ondblclick': String,
  'ondrag': String,
  'ondragend': String,
  'ondragenter': String,
  'ondragexit': String,
  'ondragleave': String,
  'ondragover': String,
  'ondragstart': String,
  'ondrop': String,
  'ondurationchange': String,
  'onemptied': String,
  'onended': String,
  'onerror': String,
  'onfocus': String,
  'oninput': String,
  'oninvalid': String,
  'onkeydown': String,
  'onkeypress': String,
  'onkeyup': String,
  'onload': String,
  'onloadeddata': String,
  'onloadedmetadata': String,
  'onloadstart': String,
  'onmousedown': String,
  'onmouseenter': String,
  'onmouseleave': String,
  'onmousemove': String,
  'onmouseout': String,
  'onmouseover': String,
  'onmouseup': String,
  'onpaste': String,
  'onpause': String,
  'onplay': String,
  'onplaying': String,
  'onprogress': String,
  'onratechange': String,
  'onreset': String,
  'onresize': String,
  'onscroll': String,
  'onseeked': String,
  'onseeking': String,
  'onselect': String,
  'onshow': String,
  'onstalled': String,
  'onsubmit': String,
  'onsuspend': String,
  'ontimeupdate': String,
  'ontoggle': String,
  'onvolumechange': String,
  'onwaiting': String,
  'onwheel': String,
  'patternContentUnits': String,
  'patternTransform': String,
  'patternUnits': String,
  'preserveAspectRatio': String,
  'style': String,
  'tabindex': String,
  'viewBox': String,
  'width': String,
  'x': String,
  'xlink:href': String,
  'xlink:title': String,
  'xml:space': String,
  'y': String
};
const pictureAttributes = {};
const polygonAttributes = {
  'autofocus': Boolean,
  'class': String,
  'id': String,
  'lang': String,
  'oncancel': String,
  'oncanplay': String,
  'oncanplaythrough': String,
  'onchange': String,
  'onclick': String,
  'onclose': String,
  'oncopy': String,
  'oncuechange': String,
  'oncut': String,
  'ondblclick': String,
  'ondrag': String,
  'ondragend': String,
  'ondragenter': String,
  'ondragexit': String,
  'ondragleave': String,
  'ondragover': String,
  'ondragstart': String,
  'ondrop': String,
  'ondurationchange': String,
  'onemptied': String,
  'onended': String,
  'onerror': String,
  'onfocus': String,
  'oninput': String,
  'oninvalid': String,
  'onkeydown': String,
  'onkeypress': String,
  'onkeyup': String,
  'onload': String,
  'onloadeddata': String,
  'onloadedmetadata': String,
  'onloadstart': String,
  'onmousedown': String,
  'onmouseenter': String,
  'onmouseleave': String,
  'onmousemove': String,
  'onmouseout': String,
  'onmouseover': String,
  'onmouseup': String,
  'onpaste': String,
  'onpause': String,
  'onplay': String,
  'onplaying': String,
  'onprogress': String,
  'onratechange': String,
  'onreset': String,
  'onresize': String,
  'onscroll': String,
  'onseeked': String,
  'onseeking': String,
  'onselect': String,
  'onshow': String,
  'onstalled': String,
  'onsubmit': String,
  'onsuspend': String,
  'ontimeupdate': String,
  'ontoggle': String,
  'onvolumechange': String,
  'onwaiting': String,
  'onwheel': String,
  'pathLength': String,
  'points': String,
  'requiredExtensions': String,
  'role': String,
  'style': String,
  'systemLanguage': String,
  'tabindex': String,
  'xml:space': ["default","preserve"]
};
const polylineAttributes = {
  'autofocus': Boolean,
  'class': String,
  'id': String,
  'lang': String,
  'oncancel': String,
  'oncanplay': String,
  'oncanplaythrough': String,
  'onchange': String,
  'onclick': String,
  'onclose': String,
  'oncopy': String,
  'oncuechange': String,
  'oncut': String,
  'ondblclick': String,
  'ondrag': String,
  'ondragend': String,
  'ondragenter': String,
  'ondragexit': String,
  'ondragleave': String,
  'ondragover': String,
  'ondragstart': String,
  'ondrop': String,
  'ondurationchange': String,
  'onemptied': String,
  'onended': String,
  'onerror': String,
  'onfocus': String,
  'oninput': String,
  'oninvalid': String,
  'onkeydown': String,
  'onkeypress': String,
  'onkeyup': String,
  'onload': String,
  'onloadeddata': String,
  'onloadedmetadata': String,
  'onloadstart': String,
  'onmousedown': String,
  'onmouseenter': String,
  'onmouseleave': String,
  'onmousemove': String,
  'onmouseout': String,
  'onmouseover': String,
  'onmouseup': String,
  'onpaste': String,
  'onpause': String,
  'onplay': String,
  'onplaying': String,
  'onprogress': String,
  'onratechange': String,
  'onreset': String,
  'onresize': String,
  'onscroll': String,
  'onseeked': String,
  'onseeking': String,
  'onselect': String,
  'onshow': String,
  'onstalled': String,
  'onsubmit': String,
  'onsuspend': String,
  'ontimeupdate': String,
  'ontoggle': String,
  'onvolumechange': String,
  'onwaiting': String,
  'onwheel': String,
  'pathLength': String,
  'points': String,
  'requiredExtensions': String,
  'role': String,
  'style': String,
  'systemLanguage': String,
  'tabindex': String,
  'xml:space': ["default","preserve"]
};
const preAttributes = {};
const progressAttributes = {
  'max': String,
  'value': [Number,String]
};
const qAttributes = {
  'cite': String
};
const radialGradientAttributes = {
  'autofocus': Boolean,
  'class': String,
  'cx': [Number,String],
  'cy': [Number,String],
  'fr': String,
  'fx': String,
  'fy': String,
  'gradientTransform': String,
  'gradientUnits': ["userSpaceOnUse","objectBoundingBox"],
  'href': String,
  'id': String,
  'lang': String,
  'oncancel': String,
  'oncanplay': String,
  'oncanplaythrough': String,
  'onchange': String,
  'onclick': String,
  'onclose': String,
  'oncopy': String,
  'oncuechange': String,
  'oncut': String,
  'ondblclick': String,
  'ondrag': String,
  'ondragend': String,
  'ondragenter': String,
  'ondragexit': String,
  'ondragleave': String,
  'ondragover': String,
  'ondragstart': String,
  'ondrop': String,
  'ondurationchange': String,
  'onemptied': String,
  'onended': String,
  'onerror': String,
  'onfocus': String,
  'oninput': String,
  'oninvalid': String,
  'onkeydown': String,
  'onkeypress': String,
  'onkeyup': String,
  'onload': String,
  'onloadeddata': String,
  'onloadedmetadata': String,
  'onloadstart': String,
  'onmousedown': String,
  'onmouseenter': String,
  'onmouseleave': String,
  'onmousemove': String,
  'onmouseout': String,
  'onmouseover': String,
  'onmouseup': String,
  'onpaste': String,
  'onpause': String,
  'onplay': String,
  'onplaying': String,
  'onprogress': String,
  'onratechange': String,
  'onreset': String,
  'onresize': String,
  'onscroll': String,
  'onseeked': String,
  'onseeking': String,
  'onselect': String,
  'onshow': String,
  'onstalled': String,
  'onsubmit': String,
  'onsuspend': String,
  'ontimeupdate': String,
  'ontoggle': String,
  'onvolumechange': String,
  'onwaiting': String,
  'onwheel': String,
  'r': [Number,String],
  'spreadMethod': String,
  'style': String,
  'tabindex': String,
  'xlink:href': String,
  'xlink:title': String,
  'xml:space': ["default","preserve"]
};
const rectAttributes = {
  'autofocus': Boolean,
  'class': String,
  'height': [Number,String],
  'id': String,
  'lang': String,
  'oncancel': String,
  'oncanplay': String,
  'oncanplaythrough': String,
  'onchange': String,
  'onclick': String,
  'onclose': String,
  'oncopy': String,
  'oncuechange': String,
  'oncut': String,
  'ondblclick': String,
  'ondrag': String,
  'ondragend': String,
  'ondragenter': String,
  'ondragexit': String,
  'ondragleave': String,
  'ondragover': String,
  'ondragstart': String,
  'ondrop': String,
  'ondurationchange': String,
  'onemptied': String,
  'onended': String,
  'onerror': String,
  'onfocus': String,
  'oninput': String,
  'oninvalid': String,
  'onkeydown': String,
  'onkeypress': String,
  'onkeyup': String,
  'onload': String,
  'onloadeddata': String,
  'onloadedmetadata': String,
  'onloadstart': String,
  'onmousedown': String,
  'onmouseenter': String,
  'onmouseleave': String,
  'onmousemove': String,
  'onmouseout': String,
  'onmouseover': String,
  'onmouseup': String,
  'onpaste': String,
  'onpause': String,
  'onplay': String,
  'onplaying': String,
  'onprogress': String,
  'onratechange': String,
  'onreset': String,
  'onresize': String,
  'onscroll': String,
  'onseeked': String,
  'onseeking': String,
  'onselect': String,
  'onshow': String,
  'onstalled': String,
  'onsubmit': String,
  'onsuspend': String,
  'ontimeupdate': String,
  'ontoggle': String,
  'onvolumechange': String,
  'onwaiting': String,
  'onwheel': String,
  'pathLength': String,
  'requiredExtensions': String,
  'role': String,
  'rx': [Number,String],
  'ry': [Number,String],
  'style': String,
  'systemLanguage': String,
  'tabindex': String,
  'width': [Number,String],
  'x': [Number,String],
  'xml:space': ["default","preserve"],
  'y': [Number,String]
};
const rpAttributes = {};
const rtAttributes = {};
const rubyAttributes = {};
const sAttributes = {};
const sampAttributes = {};
const scriptAttributes = {
  'async': Boolean,
  'blocking': String,
  'crossorigin': ["anonymous","use-credentials"],
  'defer': Boolean,
  'fetchpriority': ["auto","high","low"],
  'integrity': String,
  'nomodule': Boolean,
  'referrerpolicy': String,
  'src': String,
  'type': String
};
const searchAttributes = {};
const sectionAttributes = {};
const selectAttributes = {
  'autocomplete': String,
  'disabled': Boolean,
  'form': String,
  'multiple': Boolean,
  'name': String,
  'required': Boolean,
  'size': Number
};
const selectedcontentAttributes = {};
const setAttributes = {
  'attributeName': String,
  'autofocus': Boolean,
  'begin': String,
  'class': String,
  'dur': String,
  'end': String,
  'fill': ["remove","freeze"],
  'href': String,
  'id': String,
  'lang': String,
  'max': String,
  'min': String,
  'onbegin': String,
  'oncancel': String,
  'oncanplay': String,
  'oncanplaythrough': String,
  'onchange': String,
  'onclick': String,
  'onclose': String,
  'oncopy': String,
  'oncuechange': String,
  'oncut': String,
  'ondblclick': String,
  'ondrag': String,
  'ondragend': String,
  'ondragenter': String,
  'ondragexit': String,
  'ondragleave': String,
  'ondragover': String,
  'ondragstart': String,
  'ondrop': String,
  'ondurationchange': String,
  'onemptied': String,
  'onend': String,
  'onended': String,
  'onerror': String,
  'onfocus': String,
  'oninput': String,
  'oninvalid': String,
  'onkeydown': String,
  'onkeypress': String,
  'onkeyup': String,
  'onload': String,
  'onloadeddata': String,
  'onloadedmetadata': String,
  'onloadstart': String,
  'onmousedown': String,
  'onmouseenter': String,
  'onmouseleave': String,
  'onmousemove': String,
  'onmouseout': String,
  'onmouseover': String,
  'onmouseup': String,
  'onpaste': String,
  'onpause': String,
  'onplay': String,
  'onplaying': String,
  'onprogress': String,
  'onratechange': String,
  'onrepeat': String,
  'onreset': String,
  'onresize': String,
  'onscroll': String,
  'onseeked': String,
  'onseeking': String,
  'onselect': String,
  'onshow': String,
  'onstalled': String,
  'onsubmit': String,
  'onsuspend': String,
  'ontimeupdate': String,
  'ontoggle': String,
  'onvolumechange': String,
  'onwaiting': String,
  'onwheel': String,
  'repeatCount': String,
  'repeatDur': String,
  'requiredExtensions': String,
  'restart': ["always","never","whenNotActive"],
  'style': String,
  'systemLanguage': String,
  'tabindex': String,
  'to': String,
  'xml:space': ["default","preserve"]
};
const slotAttributes = {
  'name': String
};
const smallAttributes = {};
const sourceAttributes = {
  'height': String,
  'media': String,
  'sizes': String,
  'src': String,
  'srcset': String,
  'type': String,
  'width': String
};
const spanAttributes = {};
const stopAttributes = {
  'autofocus': Boolean,
  'class': String,
  'id': String,
  'lang': String,
  'offset': Number,
  'oncancel': String,
  'oncanplay': String,
  'oncanplaythrough': String,
  'onchange': String,
  'onclick': String,
  'onclose': String,
  'oncopy': String,
  'oncuechange': String,
  'oncut': String,
  'ondblclick': String,
  'ondrag': String,
  'ondragend': String,
  'ondragenter': String,
  'ondragexit': String,
  'ondragleave': String,
  'ondragover': String,
  'ondragstart': String,
  'ondrop': String,
  'ondurationchange': String,
  'onemptied': String,
  'onended': String,
  'onerror': String,
  'onfocus': String,
  'oninput': String,
  'oninvalid': String,
  'onkeydown': String,
  'onkeypress': String,
  'onkeyup': String,
  'onload': String,
  'onloadeddata': String,
  'onloadedmetadata': String,
  'onloadstart': String,
  'onmousedown': String,
  'onmouseenter': String,
  'onmouseleave': String,
  'onmousemove': String,
  'onmouseout': String,
  'onmouseover': String,
  'onmouseup': String,
  'onpaste': String,
  'onpause': String,
  'onplay': String,
  'onplaying': String,
  'onprogress': String,
  'onratechange': String,
  'onreset': String,
  'onresize': String,
  'onscroll': String,
  'onseeked': String,
  'onseeking': String,
  'onselect': String,
  'onshow': String,
  'onstalled': String,
  'onsubmit': String,
  'onsuspend': String,
  'ontimeupdate': String,
  'ontoggle': String,
  'onvolumechange': String,
  'onwaiting': String,
  'onwheel': String,
  'style': String,
  'tabindex': String,
  'xml:space': ["default","preserve"]
};
const strongAttributes = {};
const styleAttributes = {
  'blocking': String,
  'media': String
};
const subAttributes = {};
const summaryAttributes = {};
const supAttributes = {};
const svgAttributes = {
  'autofocus': Boolean,
  'class': String,
  'height': [Number,String],
  'id': String,
  'lang': String,
  'onabort': String,
  'oncancel': String,
  'oncanplay': String,
  'oncanplaythrough': String,
  'onchange': String,
  'onclick': String,
  'onclose': String,
  'oncopy': String,
  'oncuechange': String,
  'oncut': String,
  'ondblclick': String,
  'ondrag': String,
  'ondragend': String,
  'ondragenter': String,
  'ondragexit': String,
  'ondragleave': String,
  'ondragover': String,
  'ondragstart': String,
  'ondrop': String,
  'ondurationchange': String,
  'onemptied': String,
  'onended': String,
  'onerror': String,
  'onfocus': String,
  'oninput': String,
  'oninvalid': String,
  'onkeydown': String,
  'onkeypress': String,
  'onkeyup': String,
  'onload': String,
  'onloadeddata': String,
  'onloadedmetadata': String,
  'onloadstart': String,
  'onmousedown': String,
  'onmouseenter': String,
  'onmouseleave': String,
  'onmousemove': String,
  'onmouseout': String,
  'onmouseover': String,
  'onmouseup': String,
  'onpaste': String,
  'onpause': String,
  'onplay': String,
  'onplaying': String,
  'onprogress': String,
  'onratechange': String,
  'onreset': String,
  'onresize': String,
  'onscroll': String,
  'onseeked': String,
  'onseeking': String,
  'onselect': String,
  'onshow': String,
  'onstalled': String,
  'onsubmit': String,
  'onsuspend': String,
  'ontimeupdate': String,
  'ontoggle': String,
  'onunload': String,
  'onvolumechange': String,
  'onwaiting': String,
  'onwheel': String,
  'preserveAspectRatio': String,
  'requiredExtensions': String,
  'role': String,
  'style': String,
  'systemLanguage': String,
  'tabindex': String,
  'transform': String,
  'viewBox': String,
  'width': [Number,String],
  'x': String,
  'xml:space': ["default","preserve"],
  'y': String
};
const switchAttributes = {
  'autofocus': Boolean,
  'class': String,
  'id': String,
  'lang': String,
  'oncancel': String,
  'oncanplay': String,
  'oncanplaythrough': String,
  'onchange': String,
  'onclick': String,
  'onclose': String,
  'oncopy': String,
  'oncuechange': String,
  'oncut': String,
  'ondblclick': String,
  'ondrag': String,
  'ondragend': String,
  'ondragenter': String,
  'ondragexit': String,
  'ondragleave': String,
  'ondragover': String,
  'ondragstart': String,
  'ondrop': String,
  'ondurationchange': String,
  'onemptied': String,
  'onended': String,
  'onerror': String,
  'onfocus': String,
  'oninput': String,
  'oninvalid': String,
  'onkeydown': String,
  'onkeypress': String,
  'onkeyup': String,
  'onload': String,
  'onloadeddata': String,
  'onloadedmetadata': String,
  'onloadstart': String,
  'onmousedown': String,
  'onmouseenter': String,
  'onmouseleave': String,
  'onmousemove': String,
  'onmouseout': String,
  'onmouseover': String,
  'onmouseup': String,
  'onpaste': String,
  'onpause': String,
  'onplay': String,
  'onplaying': String,
  'onprogress': String,
  'onratechange': String,
  'onreset': String,
  'onresize': String,
  'onscroll': String,
  'onseeked': String,
  'onseeking': String,
  'onselect': String,
  'onshow': String,
  'onstalled': String,
  'onsubmit': String,
  'onsuspend': String,
  'ontimeupdate': String,
  'ontoggle': String,
  'onvolumechange': String,
  'onwaiting': String,
  'onwheel': String,
  'requiredExtensions': String,
  'role': String,
  'style': String,
  'systemLanguage': String,
  'tabindex': String,
  'xml:space': ["default","preserve"]
};
const symbolAttributes = {
  'autofocus': Boolean,
  'class': String,
  'height': String,
  'id': String,
  'lang': String,
  'oncancel': String,
  'oncanplay': String,
  'oncanplaythrough': String,
  'onchange': String,
  'onclick': String,
  'onclose': String,
  'oncopy': String,
  'oncuechange': String,
  'oncut': String,
  'ondblclick': String,
  'ondrag': String,
  'ondragend': String,
  'ondragenter': String,
  'ondragexit': String,
  'ondragleave': String,
  'ondragover': String,
  'ondragstart': String,
  'ondrop': String,
  'ondurationchange': String,
  'onemptied': String,
  'onended': String,
  'onerror': String,
  'onfocus': String,
  'oninput': String,
  'oninvalid': String,
  'onkeydown': String,
  'onkeypress': String,
  'onkeyup': String,
  'onload': String,
  'onloadeddata': String,
  'onloadedmetadata': String,
  'onloadstart': String,
  'onmousedown': String,
  'onmouseenter': String,
  'onmouseleave': String,
  'onmousemove': String,
  'onmouseout': String,
  'onmouseover': String,
  'onmouseup': String,
  'onpaste': String,
  'onpause': String,
  'onplay': String,
  'onplaying': String,
  'onprogress': String,
  'onratechange': String,
  'onreset': String,
  'onresize': String,
  'onscroll': String,
  'onseeked': String,
  'onseeking': String,
  'onselect': String,
  'onshow': String,
  'onstalled': String,
  'onsubmit': String,
  'onsuspend': String,
  'ontimeupdate': String,
  'ontoggle': String,
  'onvolumechange': String,
  'onwaiting': String,
  'onwheel': String,
  'preserveAspectRatio': String,
  'refX': String,
  'refY': String,
  'role': String,
  'style': String,
  'tabindex': String,
  'viewBox': String,
  'width': String,
  'x': String,
  'xml:space': String,
  'y': String
};
const tableAttributes = {};
const tbodyAttributes = {};
const tdAttributes = {
  'colspan': Number,
  'headers': String,
  'rowspan': String
};
const templateAttributes = {
  'shadowrootclonable': Boolean,
  'shadowrootcustomelementregistry': Boolean,
  'shadowrootdelegatesfocus': Boolean,
  'shadowrootmode': ["open","closed"],
  'shadowrootserializable': Boolean
};
const textAttributes = {
  'autofocus': Boolean,
  'class': String,
  'dx': String,
  'dy': String,
  'id': String,
  'lang': String,
  'lengthAdjust': String,
  'oncancel': String,
  'oncanplay': String,
  'oncanplaythrough': String,
  'onchange': String,
  'onclick': String,
  'onclose': String,
  'oncopy': String,
  'oncuechange': String,
  'oncut': String,
  'ondblclick': String,
  'ondrag': String,
  'ondragend': String,
  'ondragenter': String,
  'ondragexit': String,
  'ondragleave': String,
  'ondragover': String,
  'ondragstart': String,
  'ondrop': String,
  'ondurationchange': String,
  'onemptied': String,
  'onended': String,
  'onerror': String,
  'onfocus': String,
  'oninput': String,
  'oninvalid': String,
  'onkeydown': String,
  'onkeypress': String,
  'onkeyup': String,
  'onload': String,
  'onloadeddata': String,
  'onloadedmetadata': String,
  'onloadstart': String,
  'onmousedown': String,
  'onmouseenter': String,
  'onmouseleave': String,
  'onmousemove': String,
  'onmouseout': String,
  'onmouseover': String,
  'onmouseup': String,
  'onpaste': String,
  'onpause': String,
  'onplay': String,
  'onplaying': String,
  'onprogress': String,
  'onratechange': String,
  'onreset': String,
  'onresize': String,
  'onscroll': String,
  'onseeked': String,
  'onseeking': String,
  'onselect': String,
  'onshow': String,
  'onstalled': String,
  'onsubmit': String,
  'onsuspend': String,
  'ontimeupdate': String,
  'ontoggle': String,
  'onvolumechange': String,
  'onwaiting': String,
  'onwheel': String,
  'requiredExtensions': String,
  'role': String,
  'rotate': String,
  'style': String,
  'systemLanguage': String,
  'tabindex': String,
  'textLength': String,
  'x': String,
  'xml:space': ["default","preserve"],
  'y': String
};
const textareaAttributes = {
  'autocomplete': String,
  'cols': Number,
  'dirname': String,
  'disabled': Boolean,
  'form': String,
  'maxlength': String,
  'minlength': String,
  'name': String,
  'placeholder': String,
  'readonly': Boolean,
  'required': Boolean,
  'rows': Number,
  'wrap': ["soft","hard"]
};
const textPathAttributes = {
  'autofocus': Boolean,
  'class': String,
  'href': String,
  'id': String,
  'lang': String,
  'lengthAdjust': String,
  'method': String,
  'oncancel': String,
  'oncanplay': String,
  'oncanplaythrough': String,
  'onchange': String,
  'onclick': String,
  'onclose': String,
  'oncopy': String,
  'oncuechange': String,
  'oncut': String,
  'ondblclick': String,
  'ondrag': String,
  'ondragend': String,
  'ondragenter': String,
  'ondragexit': String,
  'ondragleave': String,
  'ondragover': String,
  'ondragstart': String,
  'ondrop': String,
  'ondurationchange': String,
  'onemptied': String,
  'onended': String,
  'onerror': String,
  'onfocus': String,
  'oninput': String,
  'oninvalid': String,
  'onkeydown': String,
  'onkeypress': String,
  'onkeyup': String,
  'onload': String,
  'onloadeddata': String,
  'onloadedmetadata': String,
  'onloadstart': String,
  'onmousedown': String,
  'onmouseenter': String,
  'onmouseleave': String,
  'onmousemove': String,
  'onmouseout': String,
  'onmouseover': String,
  'onmouseup': String,
  'onpaste': String,
  'onpause': String,
  'onplay': String,
  'onplaying': String,
  'onprogress': String,
  'onratechange': String,
  'onreset': String,
  'onresize': String,
  'onscroll': String,
  'onseeked': String,
  'onseeking': String,
  'onselect': String,
  'onshow': String,
  'onstalled': String,
  'onsubmit': String,
  'onsuspend': String,
  'ontimeupdate': String,
  'ontoggle': String,
  'onvolumechange': String,
  'onwaiting': String,
  'onwheel': String,
  'path': String,
  'requiredExtensions': String,
  'role': String,
  'side': String,
  'spacing': String,
  'startOffset': String,
  'style': String,
  'systemLanguage': String,
  'tabindex': String,
  'textLength': String,
  'xlink:href': String,
  'xlink:title': String,
  'xml:space': String
};
const tfootAttributes = {};
const thAttributes = {
  'abbr': String,
  'colspan': Number,
  'headers': String,
  'rowspan': String,
  'scope': ["row","ROW","col","COL","rowgroup","ROWGROUP","colgroup","COLGROUP"]
};
const theadAttributes = {};
const timeAttributes = {
  'datetime': String
};
const titleAttributes = {};
const trAttributes = {};
const trackAttributes = {
  'default': Boolean,
  'kind': ["subtitles","captions","descriptions","chapters","metadata"],
  'label': String,
  'src': String,
  'srclang': String
};
const tspanAttributes = {
  'autofocus': Boolean,
  'class': String,
  'dx': String,
  'dy': String,
  'id': String,
  'lang': String,
  'lengthAdjust': String,
  'oncancel': String,
  'oncanplay': String,
  'oncanplaythrough': String,
  'onchange': String,
  'onclick': String,
  'onclose': String,
  'oncopy': String,
  'oncuechange': String,
  'oncut': String,
  'ondblclick': String,
  'ondrag': String,
  'ondragend': String,
  'ondragenter': String,
  'ondragexit': String,
  'ondragleave': String,
  'ondragover': String,
  'ondragstart': String,
  'ondrop': String,
  'ondurationchange': String,
  'onemptied': String,
  'onended': String,
  'onerror': String,
  'onfocus': String,
  'oninput': String,
  'oninvalid': String,
  'onkeydown': String,
  'onkeypress': String,
  'onkeyup': String,
  'onload': String,
  'onloadeddata': String,
  'onloadedmetadata': String,
  'onloadstart': String,
  'onmousedown': String,
  'onmouseenter': String,
  'onmouseleave': String,
  'onmousemove': String,
  'onmouseout': String,
  'onmouseover': String,
  'onmouseup': String,
  'onpaste': String,
  'onpause': String,
  'onplay': String,
  'onplaying': String,
  'onprogress': String,
  'onratechange': String,
  'onreset': String,
  'onresize': String,
  'onscroll': String,
  'onseeked': String,
  'onseeking': String,
  'onselect': String,
  'onshow': String,
  'onstalled': String,
  'onsubmit': String,
  'onsuspend': String,
  'ontimeupdate': String,
  'ontoggle': String,
  'onvolumechange': String,
  'onwaiting': String,
  'onwheel': String,
  'requiredExtensions': String,
  'role': String,
  'rotate': String,
  'style': String,
  'systemLanguage': String,
  'tabindex': String,
  'textLength': String,
  'x': String,
  'xml:space': ["default","preserve"],
  'y': String
};
const uAttributes = {};
const ulAttributes = {};
const useAttributes = {
  'autofocus': Boolean,
  'class': String,
  'height': String,
  'href': String,
  'id': String,
  'lang': String,
  'oncancel': String,
  'oncanplay': String,
  'oncanplaythrough': String,
  'onchange': String,
  'onclick': String,
  'onclose': String,
  'oncopy': String,
  'oncuechange': String,
  'oncut': String,
  'ondblclick': String,
  'ondrag': String,
  'ondragend': String,
  'ondragenter': String,
  'ondragexit': String,
  'ondragleave': String,
  'ondragover': String,
  'ondragstart': String,
  'ondrop': String,
  'ondurationchange': String,
  'onemptied': String,
  'onended': String,
  'onerror': String,
  'onfocus': String,
  'oninput': String,
  'oninvalid': String,
  'onkeydown': String,
  'onkeypress': String,
  'onkeyup': String,
  'onload': String,
  'onloadeddata': String,
  'onloadedmetadata': String,
  'onloadstart': String,
  'onmousedown': String,
  'onmouseenter': String,
  'onmouseleave': String,
  'onmousemove': String,
  'onmouseout': String,
  'onmouseover': String,
  'onmouseup': String,
  'onpaste': String,
  'onpause': String,
  'onplay': String,
  'onplaying': String,
  'onprogress': String,
  'onratechange': String,
  'onreset': String,
  'onresize': String,
  'onscroll': String,
  'onseeked': String,
  'onseeking': String,
  'onselect': String,
  'onshow': String,
  'onstalled': String,
  'onsubmit': String,
  'onsuspend': String,
  'ontimeupdate': String,
  'ontoggle': String,
  'onvolumechange': String,
  'onwaiting': String,
  'onwheel': String,
  'requiredExtensions': String,
  'role': String,
  'style': String,
  'systemLanguage': String,
  'tabindex': String,
  'width': String,
  'x': [Number,String],
  'xlink:href': String,
  'xlink:title': String,
  'xml:space': ["default","preserve"],
  'y': [Number,String]
};
const varAttributes = {};
const videoAttributes = {
  'autoplay': Boolean,
  'controls': Boolean,
  'crossorigin': ["anonymous","use-credentials"],
  'height': String,
  'loop': Boolean,
  'muted': Boolean,
  'playsinline': Boolean,
  'poster': String,
  'preload': ["none","metadata","auto"],
  'src': String,
  'width': String
};
const viewAttributes = {
  'autofocus': Boolean,
  'class': String,
  'id': String,
  'lang': String,
  'oncancel': String,
  'oncanplay': String,
  'oncanplaythrough': String,
  'onchange': String,
  'onclick': String,
  'onclose': String,
  'oncopy': String,
  'oncuechange': String,
  'oncut': String,
  'ondblclick': String,
  'ondrag': String,
  'ondragend': String,
  'ondragenter': String,
  'ondragexit': String,
  'ondragleave': String,
  'ondragover': String,
  'ondragstart': String,
  'ondrop': String,
  'ondurationchange': String,
  'onemptied': String,
  'onended': String,
  'onerror': String,
  'onfocus': String,
  'oninput': String,
  'oninvalid': String,
  'onkeydown': String,
  'onkeypress': String,
  'onkeyup': String,
  'onload': String,
  'onloadeddata': String,
  'onloadedmetadata': String,
  'onloadstart': String,
  'onmousedown': String,
  'onmouseenter': String,
  'onmouseleave': String,
  'onmousemove': String,
  'onmouseout': String,
  'onmouseover': String,
  'onmouseup': String,
  'onpaste': String,
  'onpause': String,
  'onplay': String,
  'onplaying': String,
  'onprogress': String,
  'onratechange': String,
  'onreset': String,
  'onresize': String,
  'onscroll': String,
  'onseeked': String,
  'onseeking': String,
  'onselect': String,
  'onshow': String,
  'onstalled': String,
  'onsubmit': String,
  'onsuspend': String,
  'ontimeupdate': String,
  'ontoggle': String,
  'onvolumechange': String,
  'onwaiting': String,
  'onwheel': String,
  'preserveAspectRatio': String,
  'role': String,
  'style': String,
  'tabindex': String,
  'viewBox': String,
  'xml:space': String
};
const wbrAttributes = {};

exports.aAttributes = aAttributes;
exports.abbrAttributes = abbrAttributes;
exports.addressAttributes = addressAttributes;
exports.animateAttributes = animateAttributes;
exports.animateMotionAttributes = animateMotionAttributes;
exports.animateTransformAttributes = animateTransformAttributes;
exports.areaAttributes = areaAttributes;
exports.articleAttributes = articleAttributes;
exports.asideAttributes = asideAttributes;
exports.audioAttributes = audioAttributes;
exports.bAttributes = bAttributes;
exports.baseAttributes = baseAttributes;
exports.bdiAttributes = bdiAttributes;
exports.bdoAttributes = bdoAttributes;
exports.blockquoteAttributes = blockquoteAttributes;
exports.bodyAttributes = bodyAttributes;
exports.brAttributes = brAttributes;
exports.buttonAttributes = buttonAttributes;
exports.canvasAttributes = canvasAttributes;
exports.captionAttributes = captionAttributes;
exports.circleAttributes = circleAttributes;
exports.citeAttributes = citeAttributes;
exports.clipPathAttributes = clipPathAttributes;
exports.codeAttributes = codeAttributes;
exports.colAttributes = colAttributes;
exports.colgroupAttributes = colgroupAttributes;
exports.dataAttributes = dataAttributes;
exports.datalistAttributes = datalistAttributes;
exports.ddAttributes = ddAttributes;
exports.defsAttributes = defsAttributes;
exports.delAttributes = delAttributes;
exports.descAttributes = descAttributes;
exports.detailsAttributes = detailsAttributes;
exports.dfnAttributes = dfnAttributes;
exports.dialogAttributes = dialogAttributes;
exports.divAttributes = divAttributes;
exports.dlAttributes = dlAttributes;
exports.dtAttributes = dtAttributes;
exports.ellipseAttributes = ellipseAttributes;
exports.emAttributes = emAttributes;
exports.embedAttributes = embedAttributes;
exports.fieldsetAttributes = fieldsetAttributes;
exports.figcaptionAttributes = figcaptionAttributes;
exports.figureAttributes = figureAttributes;
exports.footerAttributes = footerAttributes;
exports.foreignObjectAttributes = foreignObjectAttributes;
exports.formAttributes = formAttributes;
exports.gAttributes = gAttributes;
exports.globalAttributes = globalAttributes;
exports.globalEvents = globalEvents;
exports.h1Attributes = h1Attributes;
exports.h2Attributes = h2Attributes;
exports.h3Attributes = h3Attributes;
exports.h4Attributes = h4Attributes;
exports.h5Attributes = h5Attributes;
exports.h6Attributes = h6Attributes;
exports.headAttributes = headAttributes;
exports.headerAttributes = headerAttributes;
exports.hgroupAttributes = hgroupAttributes;
exports.hrAttributes = hrAttributes;
exports.htmlAttributes = htmlAttributes;
exports.iAttributes = iAttributes;
exports.iframeAttributes = iframeAttributes;
exports.imageAttributes = imageAttributes;
exports.imgAttributes = imgAttributes;
exports.inputAttributes = inputAttributes;
exports.insAttributes = insAttributes;
exports.kbdAttributes = kbdAttributes;
exports.labelAttributes = labelAttributes;
exports.legendAttributes = legendAttributes;
exports.liAttributes = liAttributes;
exports.lineAttributes = lineAttributes;
exports.linearGradientAttributes = linearGradientAttributes;
exports.linkAttributes = linkAttributes;
exports.mainAttributes = mainAttributes;
exports.mapAttributes = mapAttributes;
exports.markAttributes = markAttributes;
exports.markerAttributes = markerAttributes;
exports.maskAttributes = maskAttributes;
exports.menuAttributes = menuAttributes;
exports.metaAttributes = metaAttributes;
exports.metadataAttributes = metadataAttributes;
exports.meterAttributes = meterAttributes;
exports.mpathAttributes = mpathAttributes;
exports.navAttributes = navAttributes;
exports.noscriptAttributes = noscriptAttributes;
exports.objectAttributes = objectAttributes;
exports.olAttributes = olAttributes;
exports.optgroupAttributes = optgroupAttributes;
exports.optionAttributes = optionAttributes;
exports.outputAttributes = outputAttributes;
exports.pAttributes = pAttributes;
exports.pathAttributes = pathAttributes;
exports.patternAttributes = patternAttributes;
exports.pictureAttributes = pictureAttributes;
exports.polygonAttributes = polygonAttributes;
exports.polylineAttributes = polylineAttributes;
exports.preAttributes = preAttributes;
exports.progressAttributes = progressAttributes;
exports.qAttributes = qAttributes;
exports.radialGradientAttributes = radialGradientAttributes;
exports.rectAttributes = rectAttributes;
exports.rpAttributes = rpAttributes;
exports.rtAttributes = rtAttributes;
exports.rubyAttributes = rubyAttributes;
exports.sAttributes = sAttributes;
exports.sampAttributes = sampAttributes;
exports.scriptAttributes = scriptAttributes;
exports.searchAttributes = searchAttributes;
exports.sectionAttributes = sectionAttributes;
exports.selectAttributes = selectAttributes;
exports.selectedcontentAttributes = selectedcontentAttributes;
exports.setAttributes = setAttributes;
exports.slotAttributes = slotAttributes;
exports.smallAttributes = smallAttributes;
exports.sourceAttributes = sourceAttributes;
exports.spanAttributes = spanAttributes;
exports.stopAttributes = stopAttributes;
exports.strongAttributes = strongAttributes;
exports.styleAttributes = styleAttributes;
exports.subAttributes = subAttributes;
exports.summaryAttributes = summaryAttributes;
exports.supAttributes = supAttributes;
exports.svgAttributes = svgAttributes;
exports.switchAttributes = switchAttributes;
exports.symbolAttributes = symbolAttributes;
exports.tableAttributes = tableAttributes;
exports.tbodyAttributes = tbodyAttributes;
exports.tdAttributes = tdAttributes;
exports.templateAttributes = templateAttributes;
exports.textAttributes = textAttributes;
exports.textPathAttributes = textPathAttributes;
exports.textareaAttributes = textareaAttributes;
exports.tfootAttributes = tfootAttributes;
exports.thAttributes = thAttributes;
exports.theadAttributes = theadAttributes;
exports.timeAttributes = timeAttributes;
exports.titleAttributes = titleAttributes;
exports.trAttributes = trAttributes;
exports.trackAttributes = trackAttributes;
exports.tspanAttributes = tspanAttributes;
exports.uAttributes = uAttributes;
exports.ulAttributes = ulAttributes;
exports.useAttributes = useAttributes;
exports.varAttributes = varAttributes;
exports.videoAttributes = videoAttributes;
exports.viewAttributes = viewAttributes;
exports.wbrAttributes = wbrAttributes;
