import { t } from 'kensington';

import { apiTable } from '../../components/table.js';
import { code } from '../../components/ui.js';

export function apiTagMethods() {
  return t.section({ id: 'tag-methods' }, [
    t.h2('Tag methods'),
    t.p([
      'Every HTML, SVG, and MathML element is available as a method on the ',
      t.code('Kensington'),
      ' instance. Attribute types are generated from the official specs. Each element\'s attribute type is named ',
      t.code('{PascalTag}Attributes'),
      ' (e.g. ',
      t.code('InputAttributes'),
      ', ',
      t.code('AAttributes'),
      ').',
    ]),

    t.h3({ id: 'content-elements' }, 'Content elements'),
    t.p([
      'Most elements: ',
      t.code('div'),
      ', ',
      t.code('p'),
      ', ',
      t.code('span'),
      ', ',
      t.code('section'),
      ', ',
      t.code('a'),
      ', ',
      t.code('table'),
      ', and so on.',
    ]),
    code('typescript', `t.div(attributes: DivAttributes, content?: Content): DivTag
t.div(content?: Content): DivTag`),
    t.p([
      'A subset of elements have branded return types and enforce a strict content model in TypeScript. Passing the wrong child type is a compile-time error. All strict containers also accept ',
      t.code('literal()'),
      ', ',
      t.code('inlineComment()'),
      ', ',
      t.code('null'),
      ', ',
      t.code('undefined'),
      ', and ',
      t.code('boolean'),
      ' as escape hatches for conditional patterns.',
    ]),
    apiTable(['Element(s)', 'Return type', 'Accepts'], [
      [t.code('html'), t.code('HtmlTag'), [t.code('head'), ', ', t.code('body')]],
      [
        t.code('table'),
        t.code('TableTag'),
        [
          t.code('caption'),
          ', ',
          t.code('colgroup'),
          ', ',
          t.code('thead'),
          ', ',
          t.code('tbody'),
          ', ',
          t.code('tfoot'),
          ', ',
          t.code('tr'),
        ],
      ],
      [
        [t.code('thead'), ', ', t.code('tbody'), ', ', t.code('tfoot')],
        [t.code('TheadTag'), ', ', t.code('TbodyTag'), ', ', t.code('TfootTag')],
        t.code('tr'),
      ],
      [t.code('tr'), t.code('TrTag'), [t.code('td'), ', ', t.code('th')]],
      [t.code('colgroup'), t.code('ColgroupTag'), [t.code('col'), ', ', t.code('template')]],
      [
        [t.code('ul'), ', ', t.code('ol'), ', ', t.code('menu')],
        [t.code('UlTag'), ', ', t.code('OlTag'), ', ', t.code('MenuTag')],
        t.code('li'),
      ],
      [t.code('dl'), t.code('DlTag'), [t.code('dt'), ', ', t.code('dd'), ', ', t.code('div')]],
      [
        t.code('select'),
        t.code('SelectTag'),
        [
          t.code('option'),
          ', ',
          t.code('optgroup'),
          ', ',
          t.code('hr'),
          ', ',
          t.code('div'),
          ', ',
          t.code('button'),
        ],
      ],
      [
        t.code('optgroup'),
        t.code('OptgroupTag'),
        [t.code('option'), ', ', t.code('div'), ', ', t.code('noscript'), ', ', t.code('legend')],
      ],
      [t.code('picture'), t.code('PictureTag'), [t.code('source'), ', ', t.code('img')]],
      [t.code('hgroup'), t.code('HgroupTag'), [t.code('h1'), '–', t.code('h6'), ', ', t.code('p')]],
    ]),
    t.p([
      'These elements also have branded return types but accept any ',
      t.code('Content'),
      ': ',
      t.code('td'),
      ', ',
      t.code('th'),
      ', ',
      t.code('li'),
      ', ',
      t.code('dt'),
      ', ',
      t.code('dd'),
      ', ',
      t.code('caption'),
      ', ',
      t.code('option'),
      ', ',
      t.code('body'),
      ', ',
      t.code('head'),
      ', and others. Void elements with branded types: ',
      t.code('img'),
      ' (',
      t.code('ImgTag'),
      '), ',
      t.code('col'),
      ' (',
      t.code('ColTag'),
      '), ',
      t.code('source'),
      ' (',
      t.code('SourceTag'),
      '), ',
      t.code('hr'),
      ' (',
      t.code('HrTag'),
      ').',
    ]),
    t.aside([
      t.p([
        'All branded types extend ',
        t.code('ContentTag'),
        ', so existing code typed as ',
        t.code('ContentTag'),
        ' continues to work.',
      ]),
    ]),

    t.h3({ id: 'void-elements' }, 'Void elements'),
    t.p([
      'Void elements take no content argument: ',
      t.code('br'),
      ', ',
      t.code('hr'),
      ', ',
      t.code('input'),
      ', ',
      t.code('img'),
      ', ',
      t.code('link'),
      ', ',
      t.code('meta'),
      ', ',
      t.code('source'),
      ', ',
      t.code('wbr'),
      ', and others.',
    ]),
    code('typescript', `t.input(attributes?: InputAttributes): VoidTag
t.img(attributes?: ImgAttributes): ImgTag`),
    t.aside([
      t.p([
        t.code('img'),
        ' has a branded return type (',
        t.code('ImgTag'),
        ') so it can participate in ',
        t.code('picture'),
        '\'s strict content model.',
      ]),
    ]),

    t.h3({ id: 'instance-methods' }, 'Instance methods'),
    t.p('All tag objects share these methods.'),
    apiTable(['Method', 'Returns', 'Description'], [
      [
        t.code('.toString()'),
        t.code('string'),
        'Serializes to an indented HTML string. Text content is HTML-encoded. Signal values are read as a snapshot at call time.',
      ],
      [
        t.code('.toElement()'),
        t.code('Element'),
        [
          'Creates a live DOM node. Signal attribute values, signal content, and ',
          t.code('prop'),
          ' values update the DOM in place when the signal changes. ',
          'Signal effects are stopped automatically when the element is removed from the DOM. Create the tag with ',
          t.code('{ persist: true }'),
          ' to pause effects on removal and resume them automatically on re-insertion instead of stopping permanently. Browser only. ',
          t.code('LiteralTag'),
          ' returns a ',
          t.code('DocumentFragment'),
          '; ',
          t.code('CommentTag'),
          ' returns a ',
          t.code('Comment'),
          '.',
        ],
      ],
      [
        t.code('.getDomElement()'),
        [t.code('Element'), ' | ', t.code('null')],
        [
          'Returns the live DOM element created by a prior ',
          t.code('.toElement()'),
          ' call if it is still connected to the document, otherwise ',
          t.code('null'),
          '.',
        ],
      ],
      [
        t.code('.addConnectedCallback(fn)'),
        t.code('this'),
        [
          'Registers a callback that fires when the element is inserted into the DOM. ',
          t.code('fn'),
          ' receives the live element as its first argument and as ',
          t.code('this'),
          '. Call before ',
          t.code('.toElement()'),
          '. With ',
          t.code('{ persist: true }'),
          ' the callback re-fires on every re-insertion. ',
          'Can be called multiple times to register multiple handlers.',
        ],
      ],
      [
        t.code('.addDisconnectedCallback(fn)'),
        t.code('this'),
        [
          'Registers a callback that fires when the element leaves the DOM, after signal effects are stopped (or paused for a persistent tag). With ',
          t.code('{ persist: true }'),
          ' the callback re-fires on every removal and is re-registered automatically on each reconnection, ',
          'so the full enter/leave cycle repeats without extra setup.',
        ],
      ],
    ]),
  ]);
}
